# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'V1.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
import json
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.action_chains import ActionChains
import time
import random
import requests
import json
import time
import re
import datetime
import sys
def nowINFOMAIN():
    now = datetime.datetime.now()
    prefix = str(' - [ID:MAIN/INFO] -')
    result = now.strftime("%X") + prefix
    return result
def nowERRORMAIN():
    now = datetime.datetime.now()
    prefix = str(' - [ID:MAIN/ERROR] -')
    result = now.strftime("%X") + prefix
    return result

class Ui_DropBot(object):
    def setupUi(self, DropBot):
        DropBot.setObjectName("DropBot")
        DropBot.resize(1300, 793)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DropBot.sizePolicy().hasHeightForWidth())
        DropBot.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 35, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(245, 245, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(118, 118, 113))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(157, 157, 151))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 35, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 35, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 100, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(245, 245, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 35, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(245, 245, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(118, 118, 113))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(157, 157, 151))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 35, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 35, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 100, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(245, 245, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 35, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(245, 245, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(118, 118, 113))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(157, 157, 151))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 35, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 35, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 80, 110))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 236, 226))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        DropBot.setPalette(palette)
        self.centralwidget = QtWidgets.QWidget(DropBot)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftLayout = QtWidgets.QVBoxLayout()
        self.leftLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.leftLayout.setSpacing(6)
        self.leftLayout.setObjectName("leftLayout")
        self.DropBotLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(35)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.DropBotLabel.setFont(font)
        self.DropBotLabel.setStyleSheet("font: 35pt \"Ubuntu\";")
        self.DropBotLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.DropBotLabel.setObjectName("DropBotLabel")
        self.leftLayout.addWidget(self.DropBotLabel)
        self.GridButtonsLayout = QtWidgets.QGridLayout()
        self.GridButtonsLayout.setContentsMargins(-1, 0, -1, 0)
        self.GridButtonsLayout.setSpacing(0)
        self.GridButtonsLayout.setObjectName("GridButtonsLayout")
        self.TextLabelLayout = QtWidgets.QVBoxLayout()
        self.TextLabelLayout.setObjectName("TextLabelLayout")
        self.ProfileLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ProfileLabel.sizePolicy().hasHeightForWidth())
        self.ProfileLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.ProfileLabel.setFont(font)
        self.ProfileLabel.setStyleSheet("font: 16pt \"Ubuntu\";")
        self.ProfileLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ProfileLabel.setObjectName("ProfileLabel")
        self.TextLabelLayout.addWidget(self.ProfileLabel)
        self.ModelLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ModelLabel.sizePolicy().hasHeightForWidth())
        self.ModelLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.ModelLabel.setFont(font)
        self.ModelLabel.setStyleSheet("font: 16pt \"Ubuntu\";")
        self.ModelLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ModelLabel.setObjectName("ModelLabel")
        self.TextLabelLayout.addWidget(self.ModelLabel)
        self.SizeLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SizeLabel.sizePolicy().hasHeightForWidth())
        self.SizeLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.SizeLabel.setFont(font)
        self.SizeLabel.setStyleSheet("font: 16pt \"Ubuntu\";")
        self.SizeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.SizeLabel.setObjectName("SizeLabel")
        self.TextLabelLayout.addWidget(self.SizeLabel)
        self.TaskCountLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TaskCountLabel.sizePolicy().hasHeightForWidth())
        self.TaskCountLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.TaskCountLabel.setFont(font)
        self.TaskCountLabel.setStyleSheet("font: 16pt \"Ubuntu\";")
        self.TaskCountLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.TaskCountLabel.setObjectName("TaskCountLabel")
        self.TextLabelLayout.addWidget(self.TaskCountLabel)
        self.ProxyConfigLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ProxyConfigLabel.sizePolicy().hasHeightForWidth())
        self.ProxyConfigLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.ProxyConfigLabel.setFont(font)
        self.ProxyConfigLabel.setStyleSheet("font: 16pt \"Ubuntu\";")
        self.ProxyConfigLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ProxyConfigLabel.setObjectName("ProxyConfigLabel")
        self.TextLabelLayout.addWidget(self.ProxyConfigLabel)
        self.GridButtonsLayout.addLayout(self.TextLabelLayout, 0, 0, 1, 1)
        self.LeftButtonsLayout = QtWidgets.QVBoxLayout()
        self.LeftButtonsLayout.setObjectName("LeftButtonsLayout")
        self.ProfileButtonsLayout = QtWidgets.QHBoxLayout()
        self.ProfileButtonsLayout.setContentsMargins(70, 20, 10, 20)
        self.ProfileButtonsLayout.setObjectName("ProfileButtonsLayout")
        self.ProfileComboBox = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ProfileComboBox.sizePolicy().hasHeightForWidth())
        self.ProfileComboBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        self.ProfileComboBox.setFont(font)
        self.ProfileComboBox.setStyleSheet("")
        self.ProfileComboBox.setIconSize(QtCore.QSize(16, 16))
        self.ProfileComboBox.setFrame(True)
        self.ProfileComboBox.setObjectName("ProfileComboBox")
        self.ProfileButtonsLayout.addWidget(self.ProfileComboBox)
        self.EditProfile = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EditProfile.sizePolicy().hasHeightForWidth())
        self.EditProfile.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        self.EditProfile.setFont(font)
        self.EditProfile.setStyleSheet("margin-left:10; border-radius: ")
        self.EditProfile.setObjectName("EditProfile")
        self.ProfileButtonsLayout.addWidget(self.EditProfile)
        self.LeftButtonsLayout.addLayout(self.ProfileButtonsLayout)
        self.ModelLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ModelLineEdit.sizePolicy().hasHeightForWidth())
        self.ModelLineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        self.ModelLineEdit.setFont(font)
        self.ModelLineEdit.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.ModelLineEdit.setToolTip("")
        self.ModelLineEdit.setStyleSheet(".QLineEdit {margin-left:70; margin-top:20; margin-bottom:20; margin-right:60;}")
        self.ModelLineEdit.setObjectName("ModelLineEdit")
        self.LeftButtonsLayout.addWidget(self.ModelLineEdit)
        self.SizeButtonsLayout = QtWidgets.QHBoxLayout()
        self.SizeButtonsLayout.setContentsMargins(70, 20, 10, 20)
        self.SizeButtonsLayout.setObjectName("SizeButtonsLayout")
        self.SizeComboBox = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SizeComboBox.sizePolicy().hasHeightForWidth())
        self.SizeComboBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        self.SizeComboBox.setFont(font)
        self.SizeComboBox.setStyleSheet("")
        self.SizeComboBox.setIconSize(QtCore.QSize(16, 16))
        self.SizeComboBox.setFrame(True)
        self.SizeComboBox.setObjectName("SizeComboBox")
        self.SizeButtonsLayout.addWidget(self.SizeComboBox)
        self.EditSize = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EditSize.sizePolicy().hasHeightForWidth())
        self.EditSize.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        self.EditSize.setFont(font)
        self.EditSize.setStyleSheet("margin-left:10; border-radius: ")
        self.EditSize.setObjectName("EditSize")
        self.SizeButtonsLayout.addWidget(self.EditSize)
        self.LeftButtonsLayout.addLayout(self.SizeButtonsLayout)
        self.TaskCountLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TaskCountLineEdit.sizePolicy().hasHeightForWidth())
        self.TaskCountLineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        self.TaskCountLineEdit.setFont(font)
        self.TaskCountLineEdit.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.TaskCountLineEdit.setToolTip("")
        self.TaskCountLineEdit.setStyleSheet(".QLineEdit {margin-left:70; margin-top:20; margin-bottom:20; margin-right:60;}")
        self.TaskCountLineEdit.setInputMethodHints(QtCore.Qt.ImhNone)
        self.TaskCountLineEdit.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.TaskCountLineEdit.setClearButtonEnabled(False)
        self.TaskCountLineEdit.setObjectName("TaskCountLineEdit")
        self.LeftButtonsLayout.addWidget(self.TaskCountLineEdit)
        self.ProxyConfigLayout = QtWidgets.QHBoxLayout()
        self.ProxyConfigLayout.setContentsMargins(70, 20, 10, 20)
        self.ProxyConfigLayout.setObjectName("ProxyConfigLayout")
        self.ProxyConfigComboBox = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ProxyConfigComboBox.sizePolicy().hasHeightForWidth())
        self.ProxyConfigComboBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        self.ProxyConfigComboBox.setFont(font)
        self.ProxyConfigComboBox.setAutoFillBackground(False)
        self.ProxyConfigComboBox.setStyleSheet("")
        self.ProxyConfigComboBox.setIconSize(QtCore.QSize(16, 16))
        self.ProxyConfigComboBox.setFrame(True)
        self.ProxyConfigComboBox.setObjectName("ProxyConfigComboBox")
        self.ProxyConfigLayout.addWidget(self.ProxyConfigComboBox)
        self.ProxyConfigEdit = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ProxyConfigEdit.sizePolicy().hasHeightForWidth())
        self.ProxyConfigEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        self.ProxyConfigEdit.setFont(font)
        self.ProxyConfigEdit.setStyleSheet("margin-left:10; border-radius: ")
        self.ProxyConfigEdit.setObjectName("ProxyConfigEdit")
        self.ProxyConfigLayout.addWidget(self.ProxyConfigEdit)
        self.LeftButtonsLayout.addLayout(self.ProxyConfigLayout)
        self.GridButtonsLayout.addLayout(self.LeftButtonsLayout, 0, 1, 1, 1)
        self.leftLayout.addLayout(self.GridButtonsLayout)
        self.LeftDownLayout = QtWidgets.QVBoxLayout()
        self.LeftDownLayout.setObjectName("LeftDownLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.CreateTaskButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CreateTaskButton.sizePolicy().hasHeightForWidth())
        self.CreateTaskButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.CreateTaskButton.setFont(font)
        self.CreateTaskButton.setStyleSheet("margin-left: 150; margin-right:150; margin-top: 5; margin-bottom: 5; height: 40px; padding-left: 15px; padding-right:15px;")
        self.CreateTaskButton.setObjectName("CreateTaskButton")
        self.horizontalLayout_2.addWidget(self.CreateTaskButton)
        self.LeftDownLayout.addLayout(self.horizontalLayout_2)
        self.LogOutput = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LogOutput.sizePolicy().hasHeightForWidth())
        self.LogOutput.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 35, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 35, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 35, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 100, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 236, 226))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 35, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 35, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 35, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 100, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 35, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 35, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 35, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 80, 110))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.LogOutput.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        self.LogOutput.setFont(font)
        self.LogOutput.setFocusPolicy(QtCore.Qt.NoFocus)
        self.LogOutput.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.LogOutput.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.LogOutput.setAutoFillBackground(True)
        self.LogOutput.setStyleSheet("")
        self.LogOutput.setFrameShadow(QtWidgets.QFrame.Plain)
        self.LogOutput.setLineWidth(0)
        self.LogOutput.setDocumentTitle("")
        self.LogOutput.setUndoRedoEnabled(False)
        self.LogOutput.setReadOnly(True)
        self.LogOutput.setObjectName("LogOutput")
        self.LeftDownLayout.addWidget(self.LogOutput)
        self.leftLayout.addLayout(self.LeftDownLayout)
        self.horizontalLayout.addLayout(self.leftLayout)
        self.RightLayout = QtWidgets.QVBoxLayout()
        self.RightLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.RightLayout.setObjectName("RightLayout")
        self.TaskManagerLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TaskManagerLabel.sizePolicy().hasHeightForWidth())
        self.TaskManagerLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(35)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.TaskManagerLabel.setFont(font)
        self.TaskManagerLabel.setStyleSheet("font: 35pt \"Ubuntu\";")
        self.TaskManagerLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.TaskManagerLabel.setObjectName("TaskManagerLabel")
        self.RightLayout.addWidget(self.TaskManagerLabel, 0, QtCore.Qt.AlignTop)
        self.TaskmanagerLayout = QtWidgets.QVBoxLayout()
        self.TaskmanagerLayout.setObjectName("TaskmanagerLayout")
        self.Frame = QtWidgets.QFrame(self.centralwidget)
        self.Frame.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.Frame.setStyleSheet(".QFrame {border: 0.5px solid #32414B; border-radius: 20%;}\n"
".QPushButton{height: 24px; width: 24px; background-color: rgb(228, 70, 70); background-image: url(bin.png);border: 1px solid rgb(228, 70, 70);\n"
"margin-left: auto; margin-right: auto;\n"
"border-radius: 15px;\n"
"background-repeat:no-repeat;\n"
"background-position:center;}\n"
".QPushButton:hover {\n"
"border: 2px solid white;\n"
"}"
".QLabel {font: 12pt \"Ubuntu\";}")
        self.Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Frame.setObjectName("Frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.TASKDISPLAY = QtWidgets.QGridLayout()
        self.TASKDISPLAY.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.TASKDISPLAY.setObjectName("TASKDISPLAY")
        self.PROXY0 = QtWidgets.QLabel(self.Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PROXY0.sizePolicy().hasHeightForWidth())
        self.PROXY0.setSizePolicy(sizePolicy)
        self.PROXY0.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.PROXY0.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.PROXY0.setAlignment(QtCore.Qt.AlignCenter)
        self.PROXY0.setObjectName("PROXY0")
        self.TASKDISPLAY.addWidget(self.PROXY0, 0, 1, 1, 1, QtCore.Qt.AlignTop)
        self.SITE0 = QtWidgets.QLabel(self.Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SITE0.sizePolicy().hasHeightForWidth())
        self.SITE0.setSizePolicy(sizePolicy)
        self.SITE0.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.SITE0.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.SITE0.setStyleSheet("height:32px;")
        self.SITE0.setAlignment(QtCore.Qt.AlignCenter)
        self.SITE0.setObjectName("SITE0")
        self.TASKDISPLAY.addWidget(self.SITE0, 0, 4, 1, 1, QtCore.Qt.AlignTop)
        self.SIZE1 = QtWidgets.QLabel(self.Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SIZE1.sizePolicy().hasHeightForWidth())
        self.SIZE1.setSizePolicy(sizePolicy)
        self.SIZE1.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.SIZE1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.SIZE1.setStyleSheet("")
        self.SIZE1.setAlignment(QtCore.Qt.AlignCenter)
        self.SIZE1.setObjectName("SIZE1")
        self.TASKDISPLAY.addWidget(self.SIZE1, 1, 2, 1, 1, QtCore.Qt.AlignTop)
        self.ID0 = QtWidgets.QLabel(self.Frame)
        self.ID0.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ID0.sizePolicy().hasHeightForWidth())
        self.ID0.setSizePolicy(sizePolicy)
        self.ID0.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.ID0.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ID0.setAlignment(QtCore.Qt.AlignCenter)
        self.ID0.setObjectName("ID0")
        self.TASKDISPLAY.addWidget(self.ID0, 0, 0, 1, 1, QtCore.Qt.AlignTop)
        self.MODEL0 = QtWidgets.QLabel(self.Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MODEL0.sizePolicy().hasHeightForWidth())
        self.MODEL0.setSizePolicy(sizePolicy)
        self.MODEL0.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.MODEL0.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.MODEL0.setAlignment(QtCore.Qt.AlignCenter)
        self.MODEL0.setObjectName("MODEL0")
        self.TASKDISPLAY.addWidget(self.MODEL0, 0, 3, 1, 1, QtCore.Qt.AlignTop)
        self.REMOVE0 = QtWidgets.QLabel(self.Frame)
        self.REMOVE0.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.REMOVE0.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.REMOVE0.setAlignment(QtCore.Qt.AlignCenter)
        self.REMOVE0.setObjectName("REMOVE0")
        self.TASKDISPLAY.addWidget(self.REMOVE0, 0, 6, 1, 1, QtCore.Qt.AlignTop)
        self.ID1 = QtWidgets.QLabel(self.Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ID1.sizePolicy().hasHeightForWidth())
        self.ID1.setSizePolicy(sizePolicy)
        self.ID1.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.ID1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ID1.setStyleSheet("")
        self.ID1.setAlignment(QtCore.Qt.AlignCenter)
        self.ID1.setObjectName("ID1")
        self.TASKDISPLAY.addWidget(self.ID1, 1, 0, 1, 1, QtCore.Qt.AlignTop)
        self.REMOVE1 = QtWidgets.QPushButton(self.Frame)
        self.REMOVE1.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.REMOVE1.sizePolicy().hasHeightForWidth())
        self.REMOVE1.setSizePolicy(sizePolicy)
        self.REMOVE1.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.REMOVE1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.REMOVE1.setStyleSheet("")
        self.REMOVE1.setText("")
        self.REMOVE1.setObjectName("REMOVE1")
        self.TASKDISPLAY.addWidget(self.REMOVE1, 1, 6, 1, 1, QtCore.Qt.AlignTop)
        self.MODEL1 = QtWidgets.QLabel(self.Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MODEL1.sizePolicy().hasHeightForWidth())
        self.MODEL1.setSizePolicy(sizePolicy)
        self.MODEL1.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.MODEL1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.MODEL1.setStyleSheet("")
        self.MODEL1.setAlignment(QtCore.Qt.AlignCenter)
        self.MODEL1.setObjectName("MODEL1")
        self.TASKDISPLAY.addWidget(self.MODEL1, 1, 3, 1, 1, QtCore.Qt.AlignTop)
        self.STATUS1 = QtWidgets.QLabel(self.Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.STATUS1.sizePolicy().hasHeightForWidth())
        self.STATUS1.setSizePolicy(sizePolicy)
        self.STATUS1.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.STATUS1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.STATUS1.setStyleSheet("")
        self.STATUS1.setAlignment(QtCore.Qt.AlignCenter)
        self.STATUS1.setObjectName("STATUS1")
        self.TASKDISPLAY.addWidget(self.STATUS1, 1, 5, 1, 1, QtCore.Qt.AlignTop)
        self.PROXY1 = QtWidgets.QLabel(self.Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PROXY1.sizePolicy().hasHeightForWidth())
        self.PROXY1.setSizePolicy(sizePolicy)
        self.PROXY1.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.PROXY1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.PROXY1.setStyleSheet("")
        self.PROXY1.setAlignment(QtCore.Qt.AlignCenter)
        self.PROXY1.setObjectName("PROXY1")
        self.TASKDISPLAY.addWidget(self.PROXY1, 1, 1, 1, 1, QtCore.Qt.AlignTop)
        self.SITE1 = QtWidgets.QLabel(self.Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SITE1.sizePolicy().hasHeightForWidth())
        self.SITE1.setSizePolicy(sizePolicy)
        self.SITE1.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.SITE1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.SITE1.setStyleSheet("")
        self.SITE1.setAlignment(QtCore.Qt.AlignCenter)
        self.SITE1.setObjectName("SITE1")
        self.TASKDISPLAY.addWidget(self.SITE1, 1, 4, 1, 1, QtCore.Qt.AlignTop)
        self.SIZE0 = QtWidgets.QLabel(self.Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SIZE0.sizePolicy().hasHeightForWidth())
        self.SIZE0.setSizePolicy(sizePolicy)
        self.SIZE0.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.SIZE0.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.SIZE0.setAlignment(QtCore.Qt.AlignCenter)
        self.SIZE0.setObjectName("SIZE0")
        self.TASKDISPLAY.addWidget(self.SIZE0, 0, 2, 1, 1, QtCore.Qt.AlignTop)
        self.STATUS0 = QtWidgets.QLabel(self.Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.STATUS0.sizePolicy().hasHeightForWidth())
        self.STATUS0.setSizePolicy(sizePolicy)
        self.STATUS0.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.STATUS0.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.STATUS0.setAlignment(QtCore.Qt.AlignCenter)
        self.STATUS0.setObjectName("STATUS0")
        self.TASKDISPLAY.addWidget(self.STATUS0, 0, 5, 1, 1, QtCore.Qt.AlignTop)
        self.TASKDISPLAY.setRowStretch(1, 1)
        self.verticalLayout.addLayout(self.TASKDISPLAY)
        self.TaskmanagerLayout.addWidget(self.Frame)
        self.RightLayout.addLayout(self.TaskmanagerLayout)
        self.RightLayout.setStretch(1, 1)
        self.horizontalLayout.addLayout(self.RightLayout)
        DropBot.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(DropBot)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1300, 30))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuTheme = QtWidgets.QMenu(self.menuBar)
        self.menuTheme.setObjectName("menuTheme")
        self.menuTheme_2 = QtWidgets.QMenu(self.menuTheme)
        self.menuTheme_2.setObjectName("menuTheme_2")
        DropBot.setMenuBar(self.menuBar)
        self.actionWebsite = QtWidgets.QAction(DropBot)
        self.actionWebsite.setObjectName("actionWebsite")
        self.actionEdit_profile = QtWidgets.QAction(DropBot)
        self.actionEdit_profile.setObjectName("actionEdit_profile")
        self.actionEdit_size_list = QtWidgets.QAction(DropBot)
        self.actionEdit_size_list.setObjectName("actionEdit_size_list")
        self.actionProxy_checker = QtWidgets.QAction(DropBot)
        self.actionProxy_checker.setObjectName("actionProxy_checker")
        self.actionEdit_proxy_config = QtWidgets.QAction(DropBot)
        self.actionEdit_proxy_config.setObjectName("actionEdit_proxy_config")
        self.actionDark = QtWidgets.QAction(DropBot)
        self.actionDark.setObjectName("actionDark")
        self.actionLight = QtWidgets.QAction(DropBot)
        self.actionLight.setObjectName("actionLight")
        self.menuFile.addAction(self.actionEdit_profile)
        self.menuFile.addAction(self.actionEdit_size_list)
        self.menuFile.addAction(self.actionProxy_checker)
        self.menuFile.addAction(self.actionEdit_proxy_config)
        self.menuHelp.addAction(self.actionWebsite)
        self.menuTheme_2.addAction(self.actionDark)
        self.menuTheme_2.addAction(self.actionLight)
        self.menuTheme.addAction(self.menuTheme_2.menuAction())
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuTheme.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(DropBot)
        QtCore.QMetaObject.connectSlotsByName(DropBot)

    def retranslateUi(self, DropBot):
        _translate = QtCore.QCoreApplication.translate
        DropBot.setWindowTitle(_translate("DropBot", "DropBot"))
        self.DropBotLabel.setText(_translate("DropBot", "DropBot Settings"))
        self.ProfileLabel.setText(_translate("DropBot", "Profile:"))
        self.ModelLabel.setText(_translate("DropBot", "Model:"))
        self.SizeLabel.setText(_translate("DropBot", "Size:"))
        self.TaskCountLabel.setText(_translate("DropBot", "Task count:"))
        self.ProxyConfigLabel.setText(_translate("DropBot", "Proxy config:"))
        self.EditProfile.setText(_translate("DropBot", "   Edit   "))
        self.EditProfile.clicked.connect(self.profileedit)
        self.EditSize.setText(_translate("DropBot", "   Edit   "))
        self.ProxyConfigEdit.setText(_translate("DropBot", "   Edit   "))
        self.CreateTaskButton.setText(_translate("DropBot", "ADD TASK"))
        self.LogOutput.setHtml(_translate("DropBot", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Ubuntu\';\"><br /></p></body></html>"))
        self.TaskManagerLabel.setText(_translate("DropBot", "Task Manager"))
        self.PROXY0.setText(_translate("DropBot", "PROXY"))
        self.SITE0.setText(_translate("DropBot", "SITE"))
        self.SIZE1.setText(_translate("DropBot", "12 US"))
        self.ID0.setText(_translate("DropBot", "ID"))
        self.MODEL0.setText(_translate("DropBot", "MODEL"))
        self.REMOVE0.setText(_translate("DropBot", "REMOVE THREAD"))
        self.ID1.setText(_translate("DropBot", "1"))
        self.MODEL1.setText(_translate("DropBot", "123456"))
        self.STATUS1.setText(_translate("DropBot", "example"))
        self.PROXY1.setText(_translate("DropBot", "123.123.123.123"))
        self.SITE1.setText(_translate("DropBot", "www.example.com/example"))
        self.SIZE0.setText(_translate("DropBot", "SIZE"))
        self.STATUS0.setText(_translate("DropBot", "STATUS"))
        self.menuFile.setTitle(_translate("DropBot", "File"))
        self.menuHelp.setTitle(_translate("DropBot", "Help"))
        self.menuTheme.setTitle(_translate("DropBot", "Settings"))
        self.menuTheme_2.setTitle(_translate("DropBot", "Theme"))
        self.actionWebsite.setText(_translate("DropBot", "Website"))
        self.actionEdit_profile.setText(_translate("DropBot", "Edit profile"))
        self.actionEdit_profile.triggered.connect(self.profileedit)
        self.actionEdit_size_list.setText(_translate("DropBot", "Edit size list"))
        self.actionProxy_checker.setText(_translate("DropBot", "Proxy checker"))
        self.actionEdit_proxy_config.setText(_translate("DropBot", "Edit proxy config"))
        self.actionDark.setText(_translate("DropBot", "Dark"))
        self.actionLight.setText(_translate("DropBot", "Light"))
        self.ProfileComboBox.highlighted.connect(self.loadSave)
    def loadSave(self):
        try:
            file = open('save.json', 'r', encoding='utf-8').read()
        except:
            log = nowERRORMAIN() + ' Save file not found, creating new one...\n'
            self.LogOutput.append(log)
            open('save.json', 'w', encoding='utf-8').close()
            data = open('save.json', 'r', encoding='utf-8')
            file = data.read()
            data.close()
        else:
            log = nowINFOMAIN() + ' Save file founded, loading profiles.'
            self.LogOutput.append(log)
        try:
            jsondata = json.loads(file)
        except:
            log = nowERRORMAIN() + ' Save file corrupted, creating new one...'
            self.LogOutput.append(log)
            file = open("save.json", "w+", encoding='utf-8')
            json.dump({'Profiles': []}, file)
            jsondata = json.loads(file)
            file.close()
        else:
            if file == '{"Profiles": []}':
                log = nowERRORMAIN() + ' No profiles founded, create a new one.'
                self.LogOutput.append(log)
            else:
                log = nowINFOMAIN() + ' Save file succesefully decoded.'
                self.LogOutput.append(log)
    def profileedit(self):
        dialog = QtWidgets.QDialog()
        dialog.ui = Ui_ProfileManager()
        dialog.ui.setupUi(dialog)
        dialog.exec_()
        dialog.show()



###########################################################PROFILE MANAGER#####################################################################################################################

class Ui_ProfileManager(object):
    def setupUi(self, ProfileManager):
        ProfileManager.setObjectName("ProfileManager")
        ProfileManager.resize(514, 796)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ProfileManager.sizePolicy().hasHeightForWidth())
        ProfileManager.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        ProfileManager.setPalette(palette)
        ProfileManager.setStyleSheet("")
        ProfileManager.setWindowFilePath("")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(ProfileManager)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_7 = QtWidgets.QLabel(ProfileManager)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setStyleSheet("font: 750 25pt \"Ubuntu\";")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_2.addWidget(self.label_7)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(ProfileManager)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_4 = QtWidgets.QLabel(ProfileManager)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_3 = QtWidgets.QLabel(ProfileManager)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_5 = QtWidgets.QLabel(ProfileManager)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(ProfileManager)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.label_8 = QtWidgets.QLabel(ProfileManager)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(ProfileManager)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(ProfileManager)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(ProfileManager)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.verticalLayout.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(ProfileManager)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.verticalLayout.addWidget(self.label_12)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_3.setSpacing(10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.profilename = QtWidgets.QLineEdit(ProfileManager)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.profilename.sizePolicy().hasHeightForWidth())
        self.profilename.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        self.profilename.setFont(font)
        self.profilename.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.profilename.setStyleSheet("")
        self.profilename.setInputMask("")
        self.profilename.setText("")
        self.profilename.setFrame(True)
        self.profilename.setCursorPosition(0)
        self.profilename.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.profilename.setPlaceholderText("")
        self.profilename.setObjectName("profilename")
        self.verticalLayout_3.addWidget(self.profilename)
        self.firstname = QtWidgets.QLineEdit(ProfileManager)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.firstname.sizePolicy().hasHeightForWidth())
        self.firstname.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        self.firstname.setFont(font)
        self.firstname.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.firstname.setStyleSheet("")
        self.firstname.setInputMask("")
        self.firstname.setText("")
        self.firstname.setFrame(True)
        self.firstname.setCursorPosition(0)
        self.firstname.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.firstname.setPlaceholderText("")
        self.firstname.setObjectName("firstname")
        self.verticalLayout_3.addWidget(self.firstname)
        self.lastname = QtWidgets.QLineEdit(ProfileManager)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lastname.sizePolicy().hasHeightForWidth())
        self.lastname.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        self.lastname.setFont(font)
        self.lastname.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.lastname.setStyleSheet("")
        self.lastname.setInputMask("")
        self.lastname.setText("")
        self.lastname.setFrame(True)
        self.lastname.setCursorPosition(0)
        self.lastname.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lastname.setPlaceholderText("")
        self.lastname.setObjectName("lastname")
        self.verticalLayout_3.addWidget(self.lastname)
        self.email = QtWidgets.QLineEdit(ProfileManager)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.email.sizePolicy().hasHeightForWidth())
        self.email.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        self.email.setFont(font)
        self.email.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.email.setStyleSheet("")
        self.email.setInputMask("")
        self.email.setText("")
        self.email.setFrame(True)
        self.email.setCursorPosition(0)
        self.email.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.email.setPlaceholderText("")
        self.email.setObjectName("email")
        self.verticalLayout_3.addWidget(self.email)
        self.telephone = QtWidgets.QLineEdit(ProfileManager)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.telephone.sizePolicy().hasHeightForWidth())
        self.telephone.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        self.telephone.setFont(font)
        self.telephone.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.telephone.setStyleSheet("")
        self.telephone.setInputMask("")
        self.telephone.setText("")
        self.telephone.setFrame(True)
        self.telephone.setCursorPosition(0)
        self.telephone.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.telephone.setPlaceholderText("")
        self.telephone.setObjectName("telephone")
        self.verticalLayout_3.addWidget(self.telephone)
        self.address = QtWidgets.QLineEdit(ProfileManager)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.address.sizePolicy().hasHeightForWidth())
        self.address.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        self.address.setFont(font)
        self.address.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.address.setStyleSheet("")
        self.address.setInputMask("")
        self.address.setText("")
        self.address.setFrame(True)
        self.address.setCursorPosition(0)
        self.address.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.address.setPlaceholderText("")
        self.address.setObjectName("address")
        self.verticalLayout_3.addWidget(self.address)
        self.house = QtWidgets.QLineEdit(ProfileManager)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.house.sizePolicy().hasHeightForWidth())
        self.house.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        self.house.setFont(font)
        self.house.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.house.setStyleSheet("")
        self.house.setInputMask("")
        self.house.setText("")
        self.house.setFrame(True)
        self.house.setCursorPosition(0)
        self.house.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.house.setPlaceholderText("")
        self.house.setObjectName("house")
        self.verticalLayout_3.addWidget(self.house)
        self.apartament = QtWidgets.QLineEdit(ProfileManager)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.apartament.sizePolicy().hasHeightForWidth())
        self.apartament.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        self.apartament.setFont(font)
        self.apartament.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.apartament.setStyleSheet("")
        self.apartament.setInputMask("")
        self.apartament.setText("")
        self.apartament.setFrame(True)
        self.apartament.setCursorPosition(0)
        self.apartament.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.apartament.setPlaceholderText("")
        self.apartament.setObjectName("apartament")
        self.verticalLayout_3.addWidget(self.apartament)
        self.city = QtWidgets.QLineEdit(ProfileManager)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.city.sizePolicy().hasHeightForWidth())
        self.city.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        self.city.setFont(font)
        self.city.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.city.setStyleSheet("")
        self.city.setInputMask("")
        self.city.setText("")
        self.city.setFrame(True)
        self.city.setCursorPosition(0)
        self.city.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.city.setPlaceholderText("")
        self.city.setObjectName("city")
        self.verticalLayout_3.addWidget(self.city)
        self.zipcode = QtWidgets.QLineEdit(ProfileManager)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zipcode.sizePolicy().hasHeightForWidth())
        self.zipcode.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        self.zipcode.setFont(font)
        self.zipcode.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.zipcode.setStyleSheet("")
        self.zipcode.setInputMask("")
        self.zipcode.setText("")
        self.zipcode.setFrame(True)
        self.zipcode.setCursorPosition(0)
        self.zipcode.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.zipcode.setPlaceholderText("")
        self.zipcode.setObjectName("zipcode")
        self.verticalLayout_3.addWidget(self.zipcode)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_17 = QtWidgets.QLabel(ProfileManager)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_5.addWidget(self.label_17)
        self.label_16 = QtWidgets.QLabel(ProfileManager)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_5.addWidget(self.label_16)
        self.label_15 = QtWidgets.QLabel(ProfileManager)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_5.addWidget(self.label_15)
        self.label_13 = QtWidgets.QLabel(ProfileManager)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_5.addWidget(self.label_13)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.number = QtWidgets.QLineEdit(ProfileManager)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.number.sizePolicy().hasHeightForWidth())
        self.number.setSizePolicy(sizePolicy)
        self.number.setStyleSheet("height: 20px;")
        self.number.setObjectName("number")
        self.verticalLayout_4.addWidget(self.number)
        self.owner = QtWidgets.QLineEdit(ProfileManager)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.owner.sizePolicy().hasHeightForWidth())
        self.owner.setSizePolicy(sizePolicy)
        self.owner.setStyleSheet("height: 20px;")
        self.owner.setObjectName("owner")
        self.verticalLayout_4.addWidget(self.owner)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(50)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.month = QtWidgets.QComboBox(ProfileManager)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        self.month.setFont(font)
        self.month.setStyleSheet("")
        self.month.setObjectName("month")
        self.month.addItem("")
        self.month.addItem("")
        self.month.addItem("")
        self.month.addItem("")
        self.month.addItem("")
        self.month.addItem("")
        self.month.addItem("")
        self.month.addItem("")
        self.month.addItem("")
        self.month.addItem("")
        self.month.addItem("")
        self.month.addItem("")
        self.horizontalLayout_3.addWidget(self.month)
        self.year = QtWidgets.QComboBox(ProfileManager)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        self.year.setFont(font)
        self.year.setStyleSheet("")
        self.year.setObjectName("year")
        self.year.addItem("")
        self.year.addItem("")
        self.year.addItem("")
        self.year.addItem("")
        self.year.addItem("")
        self.year.addItem("")
        self.year.addItem("")
        self.year.addItem("")
        self.year.addItem("")
        self.year.addItem("")
        self.year.addItem("")
        self.horizontalLayout_3.addWidget(self.year)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.lineEdit_2 = QtWidgets.QLineEdit(ProfileManager)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_2.setSizePolicy(sizePolicy)
        self.lineEdit_2.setStyleSheet("height: 20px;")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_4.addWidget(self.lineEdit_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.Reset = QtWidgets.QPushButton(ProfileManager)
        self.Reset.setStyleSheet("")
        self.Reset.setObjectName("Reset")
        self.horizontalLayout_4.addWidget(self.Reset)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.Save = QtWidgets.QPushButton(ProfileManager)
        self.Save.setObjectName("Save")
        self.horizontalLayout_5.addWidget(self.Save)
        self.Cancel = QtWidgets.QPushButton(ProfileManager)
        self.Cancel.setObjectName("Cancel")
        self.horizontalLayout_5.addWidget(self.Cancel)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)

        self.retranslateUi(ProfileManager)
        QtCore.QMetaObject.connectSlotsByName(ProfileManager)

    def retranslateUi(self, ProfileManager):
        _translate = QtCore.QCoreApplication.translate
        ProfileManager.setWindowTitle(_translate("ProfileManager", "Profile manager"))
        self.label_7.setText(_translate("ProfileManager", "Profile Edit"))
        self.label_2.setText(_translate("ProfileManager", "Profile name:"))
        self.label_4.setText(_translate("ProfileManager", "First name:"))
        self.label_3.setText(_translate("ProfileManager", "Last name:"))
        self.label_5.setText(_translate("ProfileManager", "Email:"))
        self.label_6.setText(_translate("ProfileManager", "Telephone:"))
        self.label_8.setText(_translate("ProfileManager", "Adress:"))
        self.label_9.setText(_translate("ProfileManager", "House number:"))
        self.label_10.setText(_translate("ProfileManager", "Apartament number:"))
        self.label_11.setText(_translate("ProfileManager", "City:"))
        self.label_12.setText(_translate("ProfileManager", "Zipcode:"))
        self.label_17.setText(_translate("ProfileManager", "Card number:"))
        self.label_16.setText(_translate("ProfileManager", "Card owner:"))
        self.label_15.setText(_translate("ProfileManager", "Expiring month/ year: "))
        self.label_13.setText(_translate("ProfileManager", "CVC/CVV2 Code:"))
        self.month.setItemText(0, _translate("ProfileManager", "01"))
        self.month.setItemText(1, _translate("ProfileManager", "02"))
        self.month.setItemText(2, _translate("ProfileManager", "03"))
        self.month.setItemText(3, _translate("ProfileManager", "04"))
        self.month.setItemText(4, _translate("ProfileManager", "05"))
        self.month.setItemText(5, _translate("ProfileManager", "06"))
        self.month.setItemText(6, _translate("ProfileManager", "07"))
        self.month.setItemText(7, _translate("ProfileManager", "08"))
        self.month.setItemText(8, _translate("ProfileManager", "09"))
        self.month.setItemText(9, _translate("ProfileManager", "10"))
        self.month.setItemText(10, _translate("ProfileManager", "11"))
        self.month.setItemText(11, _translate("ProfileManager", "12"))
        self.year.setItemText(0, _translate("ProfileManager", "2020"))
        self.year.setItemText(1, _translate("ProfileManager", "2021"))
        self.year.setItemText(2, _translate("ProfileManager", "2022"))
        self.year.setItemText(3, _translate("ProfileManager", "2023"))
        self.year.setItemText(4, _translate("ProfileManager", "2024"))
        self.year.setItemText(5, _translate("ProfileManager", "2025"))
        self.year.setItemText(6, _translate("ProfileManager", "2026"))
        self.year.setItemText(7, _translate("ProfileManager", "2027"))
        self.year.setItemText(8, _translate("ProfileManager", "2028"))
        self.year.setItemText(9, _translate("ProfileManager", "2029"))
        self.year.setItemText(10, _translate("ProfileManager", "2030"))
        self.Reset.setText(_translate("ProfileManager", "   Reset   "))
        self.Save.setText(_translate("ProfileManager", "   Save   "))
        self.Save.clicked.connect(self.saveProfile)
        self.Cancel.setText(_translate("ProfileManager", "   Cancel   "))
        self.Cancel.clicked.connect(ProfileManager.accept)
    def saveProfile(self, ProfileManager):
        try:
           field1 = self.profilename.text()
           field2 = self.firstname.text()
           field3 = self.lastname.text()
           field4 = self.email.text()
           field5 = self.telephone.text()
           field6 = self.address.text()
           field7 = self.apartament.text()
           field8 = self.house.text()
           field9 = self.city.text()
           field10 = self.zipcode.text()
           field11 = self.number.text()
           field12 = self.owner.text()
           field13 = str(self.month.currentText())
           field14 = str(self.year.currentText())
           field15 = self.lineEdit_2.text()

           data = {'profilename': field1, 'firstname': field2, 'lastname': field3, 'email': field4, 'telephone': field5, 'address': field6, 'apartament': field7, 'housenum':field8, 'city':field9, 'zipcode':field10, 'cardnum':field11, 'cardowner':field12, 'month':field13, 'year':field14, 'cvc':field15}
        except Exception as e:
            print(e)
        #Check json syntax and file existance
        try:
            f = open("save.json", "r", encoding='utf-8').read()
            json.loads(f)
        except Exception as e:
            f = open("save.json", "w", encoding='utf-8')
            json.dump({'Profiles': []}, f)
            f.close()
            print(e)
        err = False
        #Check fields
        for key, value in data.items():
            if value == '':
                err = True
        if err != True:
            try:
                write_file = open("save.json", "r+", encoding='utf-8')
                jsondata = json.loads(write_file.read())
                jsondata["Profiles"].append(data)
                write_file.close()
                open('save.json', 'w', encoding='utf-8').close()
                write_file = open("save.json", "r+", encoding='utf-8')
                json.dump(jsondata, write_file, indent=4)
                self.profilename.clear()
                self.firstname.clear()
                self.lastname.clear()
                self.email.clear()
                self.telephone.clear()
                self.address.clear()
                self.apartament.clear()
                self.house.clear()
                self.city.clear()
                self.zipcode.clear()
                self.number.clear()
                self.owner.clear()
                self.lineEdit_2.clear()
                self.month.setCurrentIndex(0)
                self.year.setCurrentIndex(0)
                write_file.close()
            except Exception as e:
                print(e)
            else:
                ui = Ui_DropBot()
                ui.setupUi(DropBot)
                ui.loadSave()
if __name__ == "__main__":
    import sys
    import qdarkstyle
    app = QtWidgets.QApplication(sys.argv)
    DropBot = QtWidgets.QMainWindow()
    app.setStyleSheet(qdarkstyle.load_stylesheet_pyqt5())
    ui = Ui_DropBot()
    ui.setupUi(DropBot)
    DropBot.show()
    ui.loadSave()
    sys.exit(app.exec_())
