# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'v1.ui',
# licensing of 'v1.ui' applies.
#
# Created: Thu Dec 12 11:33:30 2019
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, DropBot):
        DropBot.setObjectName("DropBot")
        DropBot.resize(1300, 793)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DropBot.sizePolicy().hasHeightForWidth())
        DropBot.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 236, 226))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(245, 245, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(118, 118, 113))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(157, 157, 151))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 236, 226))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(245, 245, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 236, 226))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(245, 245, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(118, 118, 113))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(157, 157, 151))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 236, 226))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(245, 245, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(118, 118, 113))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 236, 226))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(245, 245, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(118, 118, 113))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(157, 157, 151))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(118, 118, 113))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(118, 118, 113))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 236, 226))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 236, 226))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 236, 226))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        DropBot.setPalette(palette)
        DropBot.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(DropBot)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftLayout = QtWidgets.QVBoxLayout()
        self.leftLayout.setSpacing(6)
        self.leftLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.leftLayout.setObjectName("leftLayout")
        self.DropBotLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("YEEZY TSTAR")
        font.setPointSize(30)
        font.setWeight(75)
        font.setBold(True)
        self.DropBotLabel.setFont(font)
        self.DropBotLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.DropBotLabel.setObjectName("DropBotLabel")
        self.leftLayout.addWidget(self.DropBotLabel)
        self.GridButtonsLayout = QtWidgets.QGridLayout()
        self.GridButtonsLayout.setSpacing(0)
        self.GridButtonsLayout.setContentsMargins(-1, 0, -1, 0)
        self.GridButtonsLayout.setObjectName("GridButtonsLayout")
        self.TextLabelLayout = QtWidgets.QVBoxLayout()
        self.TextLabelLayout.setObjectName("TextLabelLayout")
        self.ProfileLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ProfileLabel.sizePolicy().hasHeightForWidth())
        self.ProfileLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("YEEZY TSTAR Regular")
        font.setPointSize(14)
        font.setWeight(50)
        font.setUnderline(False)
        font.setBold(False)
        self.ProfileLabel.setFont(font)
        self.ProfileLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ProfileLabel.setObjectName("ProfileLabel")
        self.TextLabelLayout.addWidget(self.ProfileLabel)
        self.ModelLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ModelLabel.sizePolicy().hasHeightForWidth())
        self.ModelLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("YEEZY TSTAR Regular")
        font.setPointSize(14)
        font.setWeight(50)
        font.setUnderline(False)
        font.setBold(False)
        self.ModelLabel.setFont(font)
        self.ModelLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ModelLabel.setObjectName("ModelLabel")
        self.TextLabelLayout.addWidget(self.ModelLabel)
        self.SizeLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SizeLabel.sizePolicy().hasHeightForWidth())
        self.SizeLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("YEEZY TSTAR Regular")
        font.setPointSize(14)
        font.setWeight(50)
        font.setUnderline(False)
        font.setBold(False)
        self.SizeLabel.setFont(font)
        self.SizeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.SizeLabel.setObjectName("SizeLabel")
        self.TextLabelLayout.addWidget(self.SizeLabel)
        self.TaskCountLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TaskCountLabel.sizePolicy().hasHeightForWidth())
        self.TaskCountLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("YEEZY TSTAR Regular")
        font.setPointSize(14)
        font.setWeight(50)
        font.setUnderline(False)
        font.setBold(False)
        self.TaskCountLabel.setFont(font)
        self.TaskCountLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.TaskCountLabel.setObjectName("TaskCountLabel")
        self.TextLabelLayout.addWidget(self.TaskCountLabel)
        self.ProxyConfigLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ProxyConfigLabel.sizePolicy().hasHeightForWidth())
        self.ProxyConfigLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("YEEZY TSTAR Regular")
        font.setPointSize(14)
        font.setWeight(50)
        font.setUnderline(False)
        font.setBold(False)
        self.ProxyConfigLabel.setFont(font)
        self.ProxyConfigLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ProxyConfigLabel.setObjectName("ProxyConfigLabel")
        self.TextLabelLayout.addWidget(self.ProxyConfigLabel)
        self.GridButtonsLayout.addLayout(self.TextLabelLayout, 0, 0, 1, 1)
        self.LeftButtonsLayout = QtWidgets.QVBoxLayout()
        self.LeftButtonsLayout.setObjectName("LeftButtonsLayout")
        self.ProfileButtonsLayout = QtWidgets.QHBoxLayout()
        self.ProfileButtonsLayout.setContentsMargins(70, 20, 10, 20)
        self.ProfileButtonsLayout.setObjectName("ProfileButtonsLayout")
        self.ProfileComboBox = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ProfileComboBox.sizePolicy().hasHeightForWidth())
        self.ProfileComboBox.setSizePolicy(sizePolicy)
        self.ProfileComboBox.setStyleSheet("")
        self.ProfileComboBox.setIconSize(QtCore.QSize(16, 16))
        self.ProfileComboBox.setFrame(True)
        self.ProfileComboBox.setObjectName("ProfileComboBox")
        self.ProfileButtonsLayout.addWidget(self.ProfileComboBox)
        self.EditProfile = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EditProfile.sizePolicy().hasHeightForWidth())
        self.EditProfile.setSizePolicy(sizePolicy)
        self.EditProfile.setStyleSheet("margin-left:10; border-radius: ")
        self.EditProfile.setObjectName("EditProfile")
        self.ProfileButtonsLayout.addWidget(self.EditProfile)
        self.LeftButtonsLayout.addLayout(self.ProfileButtonsLayout)
        self.ModelLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ModelLineEdit.sizePolicy().hasHeightForWidth())
        self.ModelLineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("YEEZY TSTAR Regular")
        font.setPointSize(10)
        self.ModelLineEdit.setFont(font)
        self.ModelLineEdit.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.ModelLineEdit.setToolTip("")
        self.ModelLineEdit.setStyleSheet(".QLineEdit {margin-left:70; margin-top:20; margin-bottom:20; margin-right:60;}")
        self.ModelLineEdit.setObjectName("ModelLineEdit")
        self.LeftButtonsLayout.addWidget(self.ModelLineEdit)
        self.SizeButtonsLayout = QtWidgets.QHBoxLayout()
        self.SizeButtonsLayout.setContentsMargins(70, 20, 10, 20)
        self.SizeButtonsLayout.setObjectName("SizeButtonsLayout")
        self.SizeComboBox = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SizeComboBox.sizePolicy().hasHeightForWidth())
        self.SizeComboBox.setSizePolicy(sizePolicy)
        self.SizeComboBox.setStyleSheet("")
        self.SizeComboBox.setIconSize(QtCore.QSize(16, 16))
        self.SizeComboBox.setFrame(True)
        self.SizeComboBox.setObjectName("SizeComboBox")
        self.SizeButtonsLayout.addWidget(self.SizeComboBox)
        self.EditSize = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EditSize.sizePolicy().hasHeightForWidth())
        self.EditSize.setSizePolicy(sizePolicy)
        self.EditSize.setStyleSheet("margin-left:10; border-radius: ")
        self.EditSize.setObjectName("EditSize")
        self.SizeButtonsLayout.addWidget(self.EditSize)
        self.LeftButtonsLayout.addLayout(self.SizeButtonsLayout)
        self.TaskCountLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TaskCountLineEdit.sizePolicy().hasHeightForWidth())
        self.TaskCountLineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("YEEZY TSTAR Regular")
        font.setPointSize(10)
        self.TaskCountLineEdit.setFont(font)
        self.TaskCountLineEdit.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.TaskCountLineEdit.setToolTip("")
        self.TaskCountLineEdit.setStyleSheet(".QLineEdit {margin-left:70; margin-top:20; margin-bottom:20; margin-right:60;}")
        self.TaskCountLineEdit.setInputMethodHints(QtCore.Qt.ImhNone)
        self.TaskCountLineEdit.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.TaskCountLineEdit.setClearButtonEnabled(False)
        self.TaskCountLineEdit.setObjectName("TaskCountLineEdit")
        self.LeftButtonsLayout.addWidget(self.TaskCountLineEdit)
        self.ProxyConfigLayout = QtWidgets.QHBoxLayout()
        self.ProxyConfigLayout.setContentsMargins(70, 20, 10, 20)
        self.ProxyConfigLayout.setObjectName("ProxyConfigLayout")
        self.ProxyConfigComboBox = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ProxyConfigComboBox.sizePolicy().hasHeightForWidth())
        self.ProxyConfigComboBox.setSizePolicy(sizePolicy)
        self.ProxyConfigComboBox.setAutoFillBackground(False)
        self.ProxyConfigComboBox.setStyleSheet("")
        self.ProxyConfigComboBox.setIconSize(QtCore.QSize(16, 16))
        self.ProxyConfigComboBox.setFrame(True)
        self.ProxyConfigComboBox.setObjectName("ProxyConfigComboBox")
        self.ProxyConfigLayout.addWidget(self.ProxyConfigComboBox)
        self.ProxyConfigEdit = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ProxyConfigEdit.sizePolicy().hasHeightForWidth())
        self.ProxyConfigEdit.setSizePolicy(sizePolicy)
        self.ProxyConfigEdit.setStyleSheet("margin-left:10; border-radius: ")
        self.ProxyConfigEdit.setObjectName("ProxyConfigEdit")
        self.ProxyConfigLayout.addWidget(self.ProxyConfigEdit)
        self.LeftButtonsLayout.addLayout(self.ProxyConfigLayout)
        self.GridButtonsLayout.addLayout(self.LeftButtonsLayout, 0, 1, 1, 1)
        self.leftLayout.addLayout(self.GridButtonsLayout)
        self.LeftDownLayout = QtWidgets.QVBoxLayout()
        self.LeftDownLayout.setObjectName("LeftDownLayout")
        self.CreateTaskButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CreateTaskButton.sizePolicy().hasHeightForWidth())
        self.CreateTaskButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("YEEZY TSTAR Bold")
        font.setPointSize(16)
        font.setWeight(75)
        font.setBold(True)
        self.CreateTaskButton.setFont(font)
        self.CreateTaskButton.setStyleSheet("margin-left: 150; margin-right:150; margin-top: 5; margin-bottom: 5; height: 40px; padding-left: 15px; padding-right:15px;")
        self.CreateTaskButton.setObjectName("CreateTaskButton")
        self.LeftDownLayout.addWidget(self.CreateTaskButton)
        self.LogOutput = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LogOutput.sizePolicy().hasHeightForWidth())
        self.LogOutput.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(236, 236, 226))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 236, 226))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 236, 226))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 236, 226))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.NoRole, brush)
        self.LogOutput.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("YEEZY TSTAR Regular")
        font.setPointSize(10)
        self.LogOutput.setFont(font)
        self.LogOutput.setFocusPolicy(QtCore.Qt.NoFocus)
        self.LogOutput.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.LogOutput.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.LogOutput.setAutoFillBackground(True)
        self.LogOutput.setStyleSheet("")
        self.LogOutput.setFrameShadow(QtWidgets.QFrame.Plain)
        self.LogOutput.setLineWidth(0)
        self.LogOutput.setDocumentTitle("")
        self.LogOutput.setUndoRedoEnabled(False)
        self.LogOutput.setReadOnly(True)
        self.LogOutput.setObjectName("LogOutput")
        self.LeftDownLayout.addWidget(self.LogOutput)
        self.leftLayout.addLayout(self.LeftDownLayout)
        self.horizontalLayout.addLayout(self.leftLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.TaskManagerLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("YEEZY TSTAR")
        font.setPointSize(30)
        font.setWeight(75)
        font.setBold(True)
        self.TaskManagerLabel.setFont(font)
        self.TaskManagerLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.TaskManagerLabel.setObjectName("TaskManagerLabel")
        self.verticalLayout.addWidget(self.TaskManagerLabel)
        self.TaskMonitor = QtWidgets.QTableWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TaskMonitor.sizePolicy().hasHeightForWidth())
        self.TaskMonitor.setSizePolicy(sizePolicy)
        self.TaskMonitor.setMinimumSize(QtCore.QSize(794, 700))
        self.TaskMonitor.setMaximumSize(QtCore.QSize(900, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(236, 236, 226))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 236, 226))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 236, 226))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 236, 226))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 236, 226))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 236, 226))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 236, 226))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 236, 226))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 236, 226))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.TaskMonitor.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("YEEZY TSTAR")
        font.setPointSize(11)
        self.TaskMonitor.setFont(font)
        self.TaskMonitor.setAutoFillBackground(True)
        self.TaskMonitor.setStyleSheet("")
        self.TaskMonitor.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.TaskMonitor.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.TaskMonitor.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.TaskMonitor.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.TaskMonitor.setAlternatingRowColors(True)
        self.TaskMonitor.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.TaskMonitor.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.TaskMonitor.setTextElideMode(QtCore.Qt.ElideNone)
        self.TaskMonitor.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.TaskMonitor.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.TaskMonitor.setShowGrid(False)
        self.TaskMonitor.setGridStyle(QtCore.Qt.NoPen)
        self.TaskMonitor.setWordWrap(False)
        self.TaskMonitor.setCornerButtonEnabled(False)
        self.TaskMonitor.setObjectName("TaskMonitor")
        self.TaskMonitor.setColumnCount(4)
        self.TaskMonitor.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.TaskMonitor.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TaskMonitor.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TaskMonitor.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.TaskMonitor.setHorizontalHeaderItem(3, item)
        self.TaskMonitor.horizontalHeader().setVisible(True)
        self.TaskMonitor.horizontalHeader().setCascadingSectionResizes(False)
        self.TaskMonitor.horizontalHeader().setDefaultSectionSize(148)
        self.TaskMonitor.horizontalHeader().setHighlightSections(False)
        self.TaskMonitor.horizontalHeader().setSortIndicatorShown(False)
        self.TaskMonitor.horizontalHeader().setStretchLastSection(True)
        self.TaskMonitor.verticalHeader().setCascadingSectionResizes(False)
        self.TaskMonitor.verticalHeader().setHighlightSections(True)
        self.TaskMonitor.verticalHeader().setSortIndicatorShown(False)
        self.TaskMonitor.verticalHeader().setStretchLastSection(False)
        self.verticalLayout.addWidget(self.TaskMonitor)
        self.horizontalLayout.addLayout(self.verticalLayout)
        DropBot.setCentralWidget(self.centralwidget)
        self.gradient = QtWidgets.QToolBar(DropBot)
        self.gradient.setAccessibleName("")
        self.gradient.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(236, 236, 226, 255));\n"
"border: 0px solid;")
        self.gradient.setMovable(False)
        self.gradient.setObjectName("gradient")
        DropBot.addToolBar(QtCore.Qt.TopToolBarArea, self.gradient)

        self.retranslateUi(DropBot)
        QtCore.QMetaObject.connectSlotsByName(DropBot)

    def retranslateUi(self, DropBot):
        DropBot.setWindowTitle(QtWidgets.QApplication.translate("DropBot", "DropBot", None, -1))
        self.DropBotLabel.setText(QtWidgets.QApplication.translate("DropBot", "DropBot Settings", None, -1))
        self.ProfileLabel.setText(QtWidgets.QApplication.translate("DropBot", "Profile:", None, -1))
        self.ModelLabel.setText(QtWidgets.QApplication.translate("DropBot", "Model:", None, -1))
        self.SizeLabel.setText(QtWidgets.QApplication.translate("DropBot", "Size:", None, -1))
        self.TaskCountLabel.setText(QtWidgets.QApplication.translate("DropBot", "Task count:", None, -1))
        self.ProxyConfigLabel.setText(QtWidgets.QApplication.translate("DropBot", "Proxy config:", None, -1))
        self.EditProfile.setText(QtWidgets.QApplication.translate("DropBot", "   Edit   ", None, -1))
        self.EditSize.setText(QtWidgets.QApplication.translate("DropBot", "   Edit   ", None, -1))
        self.ProxyConfigEdit.setText(QtWidgets.QApplication.translate("DropBot", "   Edit   ", None, -1))
        self.CreateTaskButton.setText(QtWidgets.QApplication.translate("DropBot", "ADD TASK", None, -1))
        self.LogOutput.setHtml(QtWidgets.QApplication.translate("DropBot", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'YEEZY TSTAR Regular\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'YEEZY TSTAR Regular\';\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'YEEZY TSTAR Regular\';\"><br /></p></body></html>", None, -1))
        self.TaskManagerLabel.setText(QtWidgets.QApplication.translate("DropBot", "TaskManager", None, -1))
        self.TaskMonitor.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("DropBot", "PROXY", None, -1))
        self.TaskMonitor.horizontalHeaderItem(1).setText(QtWidgets.QApplication.translate("DropBot", "SIZE", None, -1))
        self.TaskMonitor.horizontalHeaderItem(2).setText(QtWidgets.QApplication.translate("DropBot", "MODEL", None, -1))
        self.TaskMonitor.horizontalHeaderItem(3).setText(QtWidgets.QApplication.translate("DropBot", "STATUS", None, -1))
        self.gradient.setWindowTitle(QtWidgets.QApplication.translate("DropBot", "toolBar", None, -1))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DropBot = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(DropBot)
    DropBot.show()
    sys.exit(app.exec_())

