# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'V1.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
import qdarkstyle

class Ui_DropBot(object):
    def setupUi(self, DropBot):
        DropBot.setObjectName("DropBot")
        DropBot.resize(960, 621)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DropBot.sizePolicy().hasHeightForWidth())
        DropBot.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 35, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(245, 245, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(118, 118, 113))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(157, 157, 151))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 35, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 35, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 100, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(245, 245, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 35, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(245, 245, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(118, 118, 113))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(157, 157, 151))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 35, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 35, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 100, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(245, 245, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 35, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(245, 245, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(118, 118, 113))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(157, 157, 151))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 35, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 35, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 80, 110))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 236, 226))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        DropBot.setPalette(palette)
        DropBot.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(DropBot)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftLayout = QtWidgets.QVBoxLayout()
        self.leftLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.leftLayout.setSpacing(6)
        self.leftLayout.setObjectName("leftLayout")
        self.DropBotLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(35)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.DropBotLabel.setFont(font)
        self.DropBotLabel.setStyleSheet("font: 35pt \"Ubuntu\";")
        self.DropBotLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.DropBotLabel.setObjectName("DropBotLabel")
        self.leftLayout.addWidget(self.DropBotLabel)
        self.GridButtonsLayout = QtWidgets.QGridLayout()
        self.GridButtonsLayout.setContentsMargins(-1, 0, -1, 0)
        self.GridButtonsLayout.setSpacing(0)
        self.GridButtonsLayout.setObjectName("GridButtonsLayout")
        self.TextLabelLayout = QtWidgets.QVBoxLayout()
        self.TextLabelLayout.setObjectName("TextLabelLayout")
        self.ProfileLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ProfileLabel.sizePolicy().hasHeightForWidth())
        self.ProfileLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.ProfileLabel.setFont(font)
        self.ProfileLabel.setStyleSheet("font: 16pt \"Ubuntu\";")
        self.ProfileLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ProfileLabel.setObjectName("ProfileLabel")
        self.TextLabelLayout.addWidget(self.ProfileLabel)
        self.ModelLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ModelLabel.sizePolicy().hasHeightForWidth())
        self.ModelLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.ModelLabel.setFont(font)
        self.ModelLabel.setStyleSheet("font: 16pt \"Ubuntu\";")
        self.ModelLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ModelLabel.setObjectName("ModelLabel")
        self.TextLabelLayout.addWidget(self.ModelLabel)
        self.SizeLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SizeLabel.sizePolicy().hasHeightForWidth())
        self.SizeLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.SizeLabel.setFont(font)
        self.SizeLabel.setStyleSheet("font: 16pt \"Ubuntu\";")
        self.SizeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.SizeLabel.setObjectName("SizeLabel")
        self.TextLabelLayout.addWidget(self.SizeLabel)
        self.TaskCountLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TaskCountLabel.sizePolicy().hasHeightForWidth())
        self.TaskCountLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.TaskCountLabel.setFont(font)
        self.TaskCountLabel.setStyleSheet("font: 16pt \"Ubuntu\";")
        self.TaskCountLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.TaskCountLabel.setObjectName("TaskCountLabel")
        self.TextLabelLayout.addWidget(self.TaskCountLabel)
        self.ProxyConfigLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ProxyConfigLabel.sizePolicy().hasHeightForWidth())
        self.ProxyConfigLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.ProxyConfigLabel.setFont(font)
        self.ProxyConfigLabel.setStyleSheet("font: 16pt \"Ubuntu\";")
        self.ProxyConfigLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ProxyConfigLabel.setObjectName("ProxyConfigLabel")
        self.TextLabelLayout.addWidget(self.ProxyConfigLabel)
        self.WebsiteSelectLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WebsiteSelectLabel.sizePolicy().hasHeightForWidth())
        self.WebsiteSelectLabel.setSizePolicy(sizePolicy)
        self.WebsiteSelectLabel.setStyleSheet("font: 16pt \"Ubuntu\";")
        self.WebsiteSelectLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.WebsiteSelectLabel.setObjectName("WebsiteSelectLabel")
        self.TextLabelLayout.addWidget(self.WebsiteSelectLabel)
        self.GridButtonsLayout.addLayout(self.TextLabelLayout, 0, 0, 1, 1)
        self.LeftButtonsLayout = QtWidgets.QVBoxLayout()
        self.LeftButtonsLayout.setObjectName("LeftButtonsLayout")
        self.ProfileButtonsLayout = QtWidgets.QHBoxLayout()
        self.ProfileButtonsLayout.setContentsMargins(70, 15, 10, 15)
        self.ProfileButtonsLayout.setObjectName("ProfileButtonsLayout")
        self.ProfileComboBox = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ProfileComboBox.sizePolicy().hasHeightForWidth())
        self.ProfileComboBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        self.ProfileComboBox.setFont(font)
        self.ProfileComboBox.setStyleSheet("")
        self.ProfileComboBox.setIconSize(QtCore.QSize(16, 16))
        self.ProfileComboBox.setFrame(True)
        self.ProfileComboBox.setObjectName("ProfileComboBox")
        self.ProfileButtonsLayout.addWidget(self.ProfileComboBox)
        self.EditProfile = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EditProfile.sizePolicy().hasHeightForWidth())
        self.EditProfile.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        self.EditProfile.setFont(font)
        self.EditProfile.setStyleSheet("margin-left:10; border-radius: ")
        self.EditProfile.setObjectName("EditProfile")
        self.ProfileButtonsLayout.addWidget(self.EditProfile)
        self.LeftButtonsLayout.addLayout(self.ProfileButtonsLayout)
        self.ModelLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ModelLineEdit.sizePolicy().hasHeightForWidth())
        self.ModelLineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        self.ModelLineEdit.setFont(font)
        self.ModelLineEdit.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.ModelLineEdit.setToolTip("")
        self.ModelLineEdit.setStyleSheet(".QLineEdit {margin-left:70; margin-top:20; margin-bottom:20; margin-right:60;}")
        self.ModelLineEdit.setObjectName("ModelLineEdit")
        self.LeftButtonsLayout.addWidget(self.ModelLineEdit)
        self.SizeButtonsLayout = QtWidgets.QHBoxLayout()
        self.SizeButtonsLayout.setContentsMargins(70, 15, 10, 15)
        self.SizeButtonsLayout.setObjectName("SizeButtonsLayout")
        self.SizeComboBox = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SizeComboBox.sizePolicy().hasHeightForWidth())
        self.SizeComboBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        self.SizeComboBox.setFont(font)
        self.SizeComboBox.setStyleSheet("")
        self.SizeComboBox.setIconSize(QtCore.QSize(16, 16))
        self.SizeComboBox.setFrame(True)
        self.SizeComboBox.setObjectName("SizeComboBox")
        self.SizeButtonsLayout.addWidget(self.SizeComboBox)
        self.EditSize = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EditSize.sizePolicy().hasHeightForWidth())
        self.EditSize.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        self.EditSize.setFont(font)
        self.EditSize.setStyleSheet("margin-left:10; border-radius: ")
        self.EditSize.setObjectName("EditSize")
        self.SizeButtonsLayout.addWidget(self.EditSize)
        self.LeftButtonsLayout.addLayout(self.SizeButtonsLayout)
        self.TaskCountLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TaskCountLineEdit.sizePolicy().hasHeightForWidth())
        self.TaskCountLineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        self.TaskCountLineEdit.setFont(font)
        self.TaskCountLineEdit.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.TaskCountLineEdit.setToolTip("")
        self.TaskCountLineEdit.setStyleSheet(".QLineEdit {margin-left:70; margin-top:20; margin-bottom:20; margin-right:60;}")
        self.TaskCountLineEdit.setInputMethodHints(QtCore.Qt.ImhNone)
        self.TaskCountLineEdit.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.TaskCountLineEdit.setClearButtonEnabled(False)
        self.TaskCountLineEdit.setObjectName("TaskCountLineEdit")
        self.LeftButtonsLayout.addWidget(self.TaskCountLineEdit)
        self.ProxyConfigLayout = QtWidgets.QHBoxLayout()
        self.ProxyConfigLayout.setContentsMargins(70, 15, 10, 15)
        self.ProxyConfigLayout.setObjectName("ProxyConfigLayout")
        self.ProxyConfigComboBox = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ProxyConfigComboBox.sizePolicy().hasHeightForWidth())
        self.ProxyConfigComboBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        self.ProxyConfigComboBox.setFont(font)
        self.ProxyConfigComboBox.setAutoFillBackground(False)
        self.ProxyConfigComboBox.setStyleSheet("")
        self.ProxyConfigComboBox.setIconSize(QtCore.QSize(16, 16))
        self.ProxyConfigComboBox.setFrame(True)
        self.ProxyConfigComboBox.setObjectName("ProxyConfigComboBox")
        self.ProxyConfigLayout.addWidget(self.ProxyConfigComboBox)
        self.ProxyConfigEdit = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ProxyConfigEdit.sizePolicy().hasHeightForWidth())
        self.ProxyConfigEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        self.ProxyConfigEdit.setFont(font)
        self.ProxyConfigEdit.setStyleSheet("margin-left:10; border-radius: ")
        self.ProxyConfigEdit.setObjectName("ProxyConfigEdit")
        self.ProxyConfigLayout.addWidget(self.ProxyConfigEdit)
        self.LeftButtonsLayout.addLayout(self.ProxyConfigLayout)
        self.WebsiteSelectLayout = QtWidgets.QHBoxLayout()
        self.WebsiteSelectLayout.setContentsMargins(70, 15, 10, 15)
        self.WebsiteSelectLayout.setObjectName("WebsiteSelectLayout")
        self.WebsiteSelectComboBox = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WebsiteSelectComboBox.sizePolicy().hasHeightForWidth())
        self.WebsiteSelectComboBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        self.WebsiteSelectComboBox.setFont(font)
        self.WebsiteSelectComboBox.setObjectName("WebsiteSelectComboBox")
        self.WebsiteSelectLayout.addWidget(self.WebsiteSelectComboBox)
        self.LeftButtonsLayout.addLayout(self.WebsiteSelectLayout)
        self.GridButtonsLayout.addLayout(self.LeftButtonsLayout, 0, 1, 1, 1)
        self.leftLayout.addLayout(self.GridButtonsLayout)
        self.LeftDownLayout = QtWidgets.QVBoxLayout()
        self.LeftDownLayout.setObjectName("LeftDownLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.CreateTaskButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CreateTaskButton.sizePolicy().hasHeightForWidth())
        self.CreateTaskButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.CreateTaskButton.setFont(font)
        self.CreateTaskButton.setStyleSheet("margin-left: 150; margin-right:150; margin-top: 5; margin-bottom: 5; height: 40px; padding-left: 15px; padding-right:15px;")
        self.CreateTaskButton.setObjectName("CreateTaskButton")
        self.horizontalLayout_2.addWidget(self.CreateTaskButton)
        self.LeftDownLayout.addLayout(self.horizontalLayout_2)
        self.LogOutput = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LogOutput.sizePolicy().hasHeightForWidth())
        self.LogOutput.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 35, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 35, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 35, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 100, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 236, 226))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 35, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 35, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 35, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 100, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 35, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 35, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 35, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 80, 110))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.LogOutput.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        self.LogOutput.setFont(font)
        self.LogOutput.setFocusPolicy(QtCore.Qt.NoFocus)
        self.LogOutput.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.LogOutput.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.LogOutput.setAutoFillBackground(True)
        self.LogOutput.setStyleSheet("")
        self.LogOutput.setFrameShadow(QtWidgets.QFrame.Plain)
        self.LogOutput.setLineWidth(0)
        self.LogOutput.setDocumentTitle("")
        self.LogOutput.setUndoRedoEnabled(False)
        self.LogOutput.setReadOnly(True)
        self.LogOutput.setObjectName("LogOutput")
        self.LeftDownLayout.addWidget(self.LogOutput)
        self.leftLayout.addLayout(self.LeftDownLayout)
        self.horizontalLayout.addLayout(self.leftLayout)
        self.RightLayout = QtWidgets.QVBoxLayout()
        self.RightLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.RightLayout.setObjectName("RightLayout")
        self.TaskManagerLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TaskManagerLabel.sizePolicy().hasHeightForWidth())
        self.TaskManagerLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(35)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.TaskManagerLabel.setFont(font)
        self.TaskManagerLabel.setStyleSheet("font: 35pt \"Ubuntu\";")
        self.TaskManagerLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.TaskManagerLabel.setObjectName("TaskManagerLabel")
        self.RightLayout.addWidget(self.TaskManagerLabel)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        self.RightLayout.addWidget(self.tableWidget)
        self.tableWidget.verticalHeader().setVisible(False)
        self.horizontalLayout.addLayout(self.RightLayout)
        DropBot.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(DropBot)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 960, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuTheme = QtWidgets.QMenu(self.menuBar)
        self.menuTheme.setObjectName("menuTheme")
        self.menuTheme_2 = QtWidgets.QMenu(self.menuTheme)
        self.menuTheme_2.setObjectName("menuTheme_2")
        DropBot.setMenuBar(self.menuBar)
        self.actionWebsite = QtWidgets.QAction(DropBot)
        self.actionWebsite.setObjectName("actionWebsite")
        self.actionEdit_profile = QtWidgets.QAction(DropBot)
        self.actionEdit_profile.setObjectName("actionEdit_profile")
        self.actionEdit_size_list = QtWidgets.QAction(DropBot)
        self.actionEdit_size_list.setObjectName("actionEdit_size_list")
        self.actionProxy_checker = QtWidgets.QAction(DropBot)
        self.actionProxy_checker.setObjectName("actionProxy_checker")
        self.actionEdit_proxy_config = QtWidgets.QAction(DropBot)
        self.actionEdit_proxy_config.setObjectName("actionEdit_proxy_config")
        self.actionDark = QtWidgets.QAction(DropBot)
        self.actionDark.setObjectName("actionDark")
        self.actionLight = QtWidgets.QAction(DropBot)
        self.actionLight.setObjectName("actionLight")
        self.menuFile.addAction(self.actionEdit_profile)
        self.menuFile.addAction(self.actionEdit_size_list)
        self.menuFile.addAction(self.actionProxy_checker)
        self.menuFile.addAction(self.actionEdit_proxy_config)
        self.menuHelp.addAction(self.actionWebsite)
        self.menuTheme_2.addAction(self.actionDark)
        self.menuTheme_2.addAction(self.actionLight)
        self.menuTheme.addAction(self.menuTheme_2.menuAction())
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuTheme.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(DropBot)
        QtCore.QMetaObject.connectSlotsByName(DropBot)

    def retranslateUi(self, DropBot):
        _translate = QtCore.QCoreApplication.translate
        DropBot.setWindowTitle(_translate("DropBot", "MainWindow"))
        self.DropBotLabel.setText(_translate("DropBot", "DropBot Settings"))
        self.ProfileLabel.setText(_translate("DropBot", "Profile:"))
        self.ModelLabel.setText(_translate("DropBot", "Model:"))
        self.SizeLabel.setText(_translate("DropBot", "Size:"))
        self.TaskCountLabel.setText(_translate("DropBot", "Task count:"))
        self.ProxyConfigLabel.setText(_translate("DropBot", "Proxy config:"))
        self.WebsiteSelectLabel.setText(_translate("DropBot", "Website:"))
        self.EditProfile.setText(_translate("DropBot", "   Edit   "))
        self.EditSize.setText(_translate("DropBot", "   Edit   "))
        self.ProxyConfigEdit.setText(_translate("DropBot", "   Edit   "))
        self.CreateTaskButton.setText(_translate("DropBot", "ADD TASK"))
        self.LogOutput.setHtml(_translate("DropBot", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.TaskManagerLabel.setText(_translate("DropBot", "Task Manager"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("DropBot", "1"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("DropBot", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("DropBot", "NEW"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("DropBot", "NEW2"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("DropBot", "TEST"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("DropBot", "TEST"))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("DropBot", "TEST"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.menuFile.setTitle(_translate("DropBot", "File"))
        self.menuHelp.setTitle(_translate("DropBot", "Help"))
        self.menuTheme.setTitle(_translate("DropBot", "Settings"))
        self.menuTheme_2.setTitle(_translate("DropBot", "Theme"))
        self.actionWebsite.setText(_translate("DropBot", "Website"))
        self.actionEdit_profile.setText(_translate("DropBot", "Edit profile"))
        self.actionEdit_size_list.setText(_translate("DropBot", "Edit size list"))
        self.actionProxy_checker.setText(_translate("DropBot", "Proxy checker"))
        self.actionEdit_proxy_config.setText(_translate("DropBot", "Edit proxy config"))
        self.actionDark.setText(_translate("DropBot", "Dark"))
        self.actionLight.setText(_translate("DropBot", "Light"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    app.setStyleSheet(qdarkstyle.load_stylesheet_pyqt5())
    DropBot = QtWidgets.QMainWindow()
    ui = Ui_DropBot()
    ui.setupUi(DropBot)
    DropBot.show()
    sys.exit(app.exec_())
