# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'auth.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_authform(object):
    def setupUi(self, authform):
        authform.setObjectName("authform")
        authform.resize(377, 215)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        authform.setFont(font)
        authform.setStyleSheet("font: 10pt \"Ubuntu\";")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(authform)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(authform)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.AuthorizeFormTab = QtWidgets.QWidget()
        self.AuthorizeFormTab.setObjectName("AuthorizeFormTab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.AuthorizeFormTab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.AuthorizeFormTab)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.label_7 = QtWidgets.QLabel(self.AuthorizeFormTab)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(255, 185, 21);")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.AuthorizeFormTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.login = QtWidgets.QLineEdit(self.AuthorizeFormTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.login.sizePolicy().hasHeightForWidth())
        self.login.setSizePolicy(sizePolicy)
        self.login.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.login.setStyleSheet("width: 100px;")
        self.login.setObjectName("login")
        self.gridLayout.addWidget(self.login, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.AuthorizeFormTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.password = QtWidgets.QLineEdit(self.AuthorizeFormTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.password.sizePolicy().hasHeightForWidth())
        self.password.setSizePolicy(sizePolicy)
        self.password.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.password.setStyleSheet("width: 100px;")
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.gridLayout.addWidget(self.password, 2, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.submit = QtWidgets.QPushButton(self.AuthorizeFormTab)
        self.submit.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.submit.setObjectName("submit")
        self.horizontalLayout.addWidget(self.submit)
        self.cancel = QtWidgets.QPushButton(self.AuthorizeFormTab)
        self.cancel.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.cancel.setObjectName("cancel")
        self.horizontalLayout.addWidget(self.cancel)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tabWidget.addTab(self.AuthorizeFormTab, "")
        self.ServerStatusTab = QtWidgets.QWidget()
        self.ServerStatusTab.setObjectName("ServerStatusTab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.ServerStatusTab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.ServerStatusTab)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.ServerStatusTab)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.ServerStatusTab)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 2, 0, 1, 1)
        self.server2Status = QtWidgets.QLabel(self.ServerStatusTab)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.server2Status.setFont(font)
        self.server2Status.setStyleSheet("color: rgb(255, 185, 21);")
        self.server2Status.setObjectName("server2Status")
        self.gridLayout_2.addWidget(self.server2Status, 1, 2, 1, 1)
        self.server1Status = QtWidgets.QLabel(self.ServerStatusTab)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.server1Status.setFont(font)
        self.server1Status.setStyleSheet("color: rgb(255, 185, 21);")
        self.server1Status.setObjectName("server1Status")
        self.gridLayout_2.addWidget(self.server1Status, 0, 2, 1, 1)
        self.server3Status = QtWidgets.QLabel(self.ServerStatusTab)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.server3Status.setFont(font)
        self.server3Status.setStyleSheet("color: rgb(255, 185, 21);")
        self.server3Status.setObjectName("server3Status")
        self.gridLayout_2.addWidget(self.server3Status, 2, 2, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.pushButton = QtWidgets.QPushButton(self.ServerStatusTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.tabWidget.addTab(self.ServerStatusTab, "")
        self.verticalLayout_2.addWidget(self.tabWidget)

        self.retranslateUi(authform)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(authform)

    def retranslateUi(self, authform):
        _translate = QtCore.QCoreApplication.translate
        authform.setWindowTitle(_translate("authform", "DropBot Authorizing."))
        self.label.setText(_translate("authform", "Please authorize to DropBot.site"))
        self.label_7.setText(_translate("authform", "   Loading...   "))
        self.label_3.setText(_translate("authform", "Password"))
        self.label_2.setText(_translate("authform", "Login"))
        self.submit.setText(_translate("authform", "Submit"))
        self.cancel.setText(_translate("authform", "Cancel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.AuthorizeFormTab), _translate("authform", "Auth"))
        self.label_4.setText(_translate("authform", "   API Server   "))
        self.label_5.setText(_translate("authform", "   DropBot Server   "))
        self.label_6.setText(_translate("authform", "   Google API   "))
        self.server2Status.setText(_translate("authform", "Loading.."))
        self.server1Status.setText(_translate("authform", "Loading.."))
        self.server3Status.setText(_translate("authform", "Loading.."))
        self.pushButton.setText(_translate("authform", "Update"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ServerStatusTab), _translate("authform", "Servers status"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    authform = QtWidgets.QDialog()
    ui = Ui_authform()
    ui.setupUi(authform)
    authform.show()
    sys.exit(app.exec_())
