# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SizeHelp.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SizeChart(object):
    def setupUi(self, SizeChart):
        SizeChart.setObjectName("SizeChart")
        SizeChart.resize(823, 685)
        SizeChart.setMinimumSize(QtCore.QSize(823, 685))
        SizeChart.setMaximumSize(QtCore.QSize(823, 685))
        self.verticalLayout = QtWidgets.QVBoxLayout(SizeChart)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(SizeChart)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(28)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.textBrowser = QtWidgets.QTextBrowser(SizeChart)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        self.textBrowser.setFont(font)
        self.textBrowser.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.textBrowser.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.textBrowser.setStyleSheet("")
        self.textBrowser.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.textBrowser.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.pushButton = QtWidgets.QPushButton(SizeChart)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(SizeChart)
        QtCore.QMetaObject.connectSlotsByName(SizeChart)

    def retranslateUi(self, SizeChart):
        _translate = QtCore.QCoreApplication.translate
        SizeChart.setWindowTitle(_translate("SizeChart", "Dialog"))
        self.label.setText(_translate("SizeChart", "International shoe convertion chart"))
        self.textBrowser.setHtml(_translate("SizeChart", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Ubuntu\';\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt;\">Adult Mens and Womens Shoe Size Conversion Table<br /></span><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#ff6600;\">M/W indicates Men\'s or Women\'s Sizes. Other systems are for either gender.</span></p>\n"
"<table border=\"2\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px;\" align=\"center\" cellspacing=\"0\" cellpadding=\"4\">\n"
"<tr>\n"
"<td colspan=\"2\" bgcolor=\"#ffcc66\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; font-weight:600; color:#0000ff; background-color:#ffcc66;\">System</span></p></td>\n"
"<td colspan=\"16\" bgcolor=\"#ffcc66\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; font-weight:600; color:#0000ff; background-color:#ffcc66;\">Sizes</span></p></td>\n"
"<td colspan=\"2\" bgcolor=\"#ffcc66\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; font-weight:600; color:#0000ff; background-color:#ffcc66;\">System</span></p></td></tr>\n"
"<tr>\n"
"<td colspan=\"2\" bgcolor=\"#ffffcc\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; font-weight:600; color:#000000; background-color:#ffffcc;\">Europe</span></p></td>\n"
"<td bgcolor=\"#ffffcc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffcc;\">35</span></p></td>\n"
"<td bgcolor=\"#ffffcc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffcc;\">35½</span></p></td>\n"
"<td bgcolor=\"#ffffcc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffcc;\">36</span></p></td>\n"
"<td bgcolor=\"#ffffcc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffcc;\">37</span></p></td>\n"
"<td bgcolor=\"#ffffcc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffcc;\">37½</span></p></td>\n"
"<td bgcolor=\"#ffffcc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffcc;\">38</span></p></td>\n"
"<td bgcolor=\"#ffffcc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffcc;\">38½</span></p></td>\n"
"<td bgcolor=\"#ffffcc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffcc;\">39</span></p></td>\n"
"<td bgcolor=\"#ffffcc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffcc;\">40</span></p></td>\n"
"<td bgcolor=\"#ffffcc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffcc;\">41</span></p></td>\n"
"<td bgcolor=\"#ffffcc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffcc;\">42</span></p></td>\n"
"<td bgcolor=\"#ffffcc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffcc;\">43</span></p></td>\n"
"<td bgcolor=\"#ffffcc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffcc;\">44</span></p></td>\n"
"<td bgcolor=\"#ffffcc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffcc;\">45</span></p></td>\n"
"<td bgcolor=\"#ffffcc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffcc;\">46½</span></p></td>\n"
"<td bgcolor=\"#ffffcc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffcc;\">48½</span></p></td>\n"
"<td colspan=\"2\" bgcolor=\"#ffffcc\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; font-weight:600; color:#000000; background-color:#ffffcc;\">Europe</span></p></td></tr>\n"
"<tr>\n"
"<td colspan=\"2\" bgcolor=\"#ccccff\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; font-weight:600; color:#000000; background-color:#ccccff;\">Mexico</span></p></td>\n"
"<td bgcolor=\"#ccccff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ccccff;\"> </span></p></td>\n"
"<td bgcolor=\"#ccccff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ccccff;\"> </span></p></td>\n"
"<td bgcolor=\"#ccccff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ccccff;\"> </span></p></td>\n"
"<td bgcolor=\"#ccccff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ccccff;\"> </span></p></td>\n"
"<td bgcolor=\"#ccccff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ccccff;\"> </span></p></td>\n"
"<td bgcolor=\"#ccccff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ccccff;\">4.5</span></p></td>\n"
"<td bgcolor=\"#ccccff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ccccff;\">5</span></p></td>\n"
"<td bgcolor=\"#ccccff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ccccff;\">5.5</span></p></td>\n"
"<td bgcolor=\"#ccccff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ccccff;\">6</span></p></td>\n"
"<td bgcolor=\"#ccccff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ccccff;\">6.5</span></p></td>\n"
"<td bgcolor=\"#ccccff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ccccff;\">7</span></p></td>\n"
"<td bgcolor=\"#ccccff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ccccff;\">7.5</span></p></td>\n"
"<td bgcolor=\"#ccccff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ccccff;\">9</span></p></td>\n"
"<td bgcolor=\"#ccccff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ccccff;\">10</span></p></td>\n"
"<td bgcolor=\"#ccccff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ccccff;\">11</span></p></td>\n"
"<td bgcolor=\"#ccccff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ccccff;\">12.5</span></p></td>\n"
"<td colspan=\"2\" bgcolor=\"#ccccff\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; font-weight:600; color:#000000; background-color:#ccccff;\">Mexico</span></p></td></tr>\n"
"<tr>\n"
"<td rowspan=\"2\" bgcolor=\"#ffccff\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; font-weight:600; color:#000000; background-color:#ffccff;\">Japan</span></p></td>\n"
"<td bgcolor=\"#ffccff\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; font-weight:600; color:#000000; background-color:#ffccff;\">M</span></p></td>\n"
"<td bgcolor=\"#ffccff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffccff;\">21.5</span></p></td>\n"
"<td bgcolor=\"#ffccff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffccff;\">22</span></p></td>\n"
"<td bgcolor=\"#ffccff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffccff;\">22.5</span></p></td>\n"
"<td bgcolor=\"#ffccff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffccff;\">23</span></p></td>\n"
"<td bgcolor=\"#ffccff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffccff;\">23.5</span></p></td>\n"
"<td bgcolor=\"#ffccff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffccff;\">24</span></p></td>\n"
"<td bgcolor=\"#ffccff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffccff;\">24.5</span></p></td>\n"
"<td bgcolor=\"#ffccff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffccff;\">25</span></p></td>\n"
"<td bgcolor=\"#ffccff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffccff;\">25.5</span></p></td>\n"
"<td bgcolor=\"#ffccff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffccff;\">26</span></p></td>\n"
"<td bgcolor=\"#ffccff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffccff;\">26.5</span></p></td>\n"
"<td bgcolor=\"#ffccff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffccff;\">27.5</span></p></td>\n"
"<td bgcolor=\"#ffccff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffccff;\">28.5</span></p></td>\n"
"<td bgcolor=\"#ffccff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffccff;\">29.5</span></p></td>\n"
"<td bgcolor=\"#ffccff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffccff;\">30.5</span></p></td>\n"
"<td bgcolor=\"#ffccff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffccff;\">31.5</span></p></td>\n"
"<td bgcolor=\"#ffccff\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; font-weight:600; color:#000000; background-color:#ffccff;\">Japan</span></p></td>\n"
"<td bgcolor=\"#ffccff\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; font-weight:600; color:#000000; background-color:#ffccff;\">M</span></p></td></tr>\n"
"<tr>\n"
"<td bgcolor=\"#ffffff\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; font-weight:600; color:#000000; background-color:#ffffff;\">W</span></p></td>\n"
"<td bgcolor=\"#ffffff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffff;\">21</span></p></td>\n"
"<td bgcolor=\"#ffffff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffff;\">21.5</span></p></td>\n"
"<td bgcolor=\"#ffffff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffff;\">22</span></p></td>\n"
"<td bgcolor=\"#ffffff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffff;\">22.5</span></p></td>\n"
"<td bgcolor=\"#ffffff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffff;\">23</span></p></td>\n"
"<td bgcolor=\"#ffffff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffff;\">23.5</span></p></td>\n"
"<td bgcolor=\"#ffffff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffff;\">24</span></p></td>\n"
"<td bgcolor=\"#ffffff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffff;\">24.5</span></p></td>\n"
"<td bgcolor=\"#ffffff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffff;\">25</span></p></td>\n"
"<td bgcolor=\"#ffffff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffff;\">25.5</span></p></td>\n"
"<td bgcolor=\"#ffffff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffff;\">26</span></p></td>\n"
"<td bgcolor=\"#ffffff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffff;\">27</span></p></td>\n"
"<td bgcolor=\"#ffffff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffff;\">28</span></p></td>\n"
"<td bgcolor=\"#ffffff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffff;\">29</span></p></td>\n"
"<td bgcolor=\"#ffffff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffff;\">30</span></p></td>\n"
"<td bgcolor=\"#ffffff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffff;\">31</span></p></td>\n"
"<td bgcolor=\"#ffffff\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; font-weight:600; color:#000000; background-color:#ffffff;\">Japan</span></p></td>\n"
"<td bgcolor=\"#ffffff\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; font-weight:600; color:#000000; background-color:#ffffff;\">W</span></p></td></tr>\n"
"<tr>\n"
"<td rowspan=\"2\" bgcolor=\"#ffcc99\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; font-weight:600; color:#000000; background-color:#ffcc99;\">U.K.</span></p></td>\n"
"<td bgcolor=\"#ffcc99\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; font-weight:600; color:#000000; background-color:#ffcc99;\">M</span></p></td>\n"
"<td bgcolor=\"#ffcc99\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffcc99;\">3</span></p></td>\n"
"<td bgcolor=\"#ffcc99\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffcc99;\">3½</span></p></td>\n"
"<td bgcolor=\"#ffcc99\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffcc99;\">4</span></p></td>\n"
"<td bgcolor=\"#ffcc99\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffcc99;\">4½</span></p></td>\n"
"<td bgcolor=\"#ffcc99\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffcc99;\">5</span></p></td>\n"
"<td bgcolor=\"#ffcc99\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffcc99;\">5½</span></p></td>\n"
"<td bgcolor=\"#ffcc99\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffcc99;\">6</span></p></td>\n"
"<td bgcolor=\"#ffcc99\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffcc99;\">6½</span></p></td>\n"
"<td bgcolor=\"#ffcc99\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffcc99;\">7</span></p></td>\n"
"<td bgcolor=\"#ffcc99\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffcc99;\">7½</span></p></td>\n"
"<td bgcolor=\"#ffcc99\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffcc99;\">8</span></p></td>\n"
"<td bgcolor=\"#ffcc99\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffcc99;\">8½</span></p></td>\n"
"<td bgcolor=\"#ffcc99\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffcc99;\">10</span></p></td>\n"
"<td bgcolor=\"#ffcc99\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffcc99;\">11</span></p></td>\n"
"<td bgcolor=\"#ffcc99\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffcc99;\">12</span></p></td>\n"
"<td bgcolor=\"#ffcc99\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffcc99;\">13½</span></p></td>\n"
"<td bgcolor=\"#ffcc99\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; font-weight:600; color:#000000; background-color:#ffcc99;\">U.K.</span></p></td>\n"
"<td bgcolor=\"#ffcc99\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; font-weight:600; color:#000000; background-color:#ffcc99;\">M</span></p></td></tr>\n"
"<tr>\n"
"<td bgcolor=\"#ffffff\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; font-weight:600; color:#000000; background-color:#ffffff;\">W</span></p></td>\n"
"<td bgcolor=\"#ffffff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffff;\">2½</span></p></td>\n"
"<td bgcolor=\"#ffffff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffff;\">3</span></p></td>\n"
"<td bgcolor=\"#ffffff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffff;\">3½</span></p></td>\n"
"<td bgcolor=\"#ffffff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffff;\">4</span></p></td>\n"
"<td bgcolor=\"#ffffff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffff;\">4½</span></p></td>\n"
"<td bgcolor=\"#ffffff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffff;\">5</span></p></td>\n"
"<td bgcolor=\"#ffffff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffff;\">5½</span></p></td>\n"
"<td bgcolor=\"#ffffff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffff;\">6</span></p></td>\n"
"<td bgcolor=\"#ffffff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffff;\">6½</span></p></td>\n"
"<td bgcolor=\"#ffffff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffff;\">7</span></p></td>\n"
"<td bgcolor=\"#ffffff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffff;\">7½</span></p></td>\n"
"<td bgcolor=\"#ffffff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffff;\">8</span></p></td>\n"
"<td bgcolor=\"#ffffff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffff;\">9½</span></p></td>\n"
"<td bgcolor=\"#ffffff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffff;\">10½</span></p></td>\n"
"<td bgcolor=\"#ffffff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffff;\">11½</span></p></td>\n"
"<td bgcolor=\"#ffffff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffff;\">13</span></p></td>\n"
"<td bgcolor=\"#ffffff\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; font-weight:600; color:#000000; background-color:#ffffff;\">U.K.</span></p></td>\n"
"<td bgcolor=\"#ffffff\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; font-weight:600; color:#000000; background-color:#ffffff;\">W</span></p></td></tr>\n"
"<tr>\n"
"<td rowspan=\"2\" bgcolor=\"#ffffcc\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; font-weight:600; color:#000000; background-color:#ffffcc;\">Australia</span></p></td>\n"
"<td bgcolor=\"#ffffcc\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; font-weight:600; color:#000000; background-color:#ffffcc;\">M</span></p></td>\n"
"<td bgcolor=\"#ffffcc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffcc;\">3</span></p></td>\n"
"<td bgcolor=\"#ffffcc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffcc;\">3½</span></p></td>\n"
"<td bgcolor=\"#ffffcc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffcc;\">4</span></p></td>\n"
"<td bgcolor=\"#ffffcc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffcc;\">4½</span></p></td>\n"
"<td bgcolor=\"#ffffcc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffcc;\">5</span></p></td>\n"
"<td bgcolor=\"#ffffcc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffcc;\">5½</span></p></td>\n"
"<td bgcolor=\"#ffffcc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffcc;\">6</span></p></td>\n"
"<td bgcolor=\"#ffffcc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffcc;\">6½</span></p></td>\n"
"<td bgcolor=\"#ffffcc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffcc;\">7</span></p></td>\n"
"<td bgcolor=\"#ffffcc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffcc;\">7½</span></p></td>\n"
"<td bgcolor=\"#ffffcc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffcc;\">8</span></p></td>\n"
"<td bgcolor=\"#ffffcc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffcc;\">8½</span></p></td>\n"
"<td bgcolor=\"#ffffcc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffcc;\">10</span></p></td>\n"
"<td bgcolor=\"#ffffcc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffcc;\">11</span></p></td>\n"
"<td bgcolor=\"#ffffcc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffcc;\">12</span></p></td>\n"
"<td bgcolor=\"#ffffcc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffcc;\">13½</span></p></td>\n"
"<td bgcolor=\"#ffffcc\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; font-weight:600; color:#000000; background-color:#ffffcc;\">Australia</span></p></td>\n"
"<td bgcolor=\"#ffffcc\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; font-weight:600; color:#000000; background-color:#ffffcc;\">M</span></p></td></tr>\n"
"<tr>\n"
"<td bgcolor=\"#cccccc\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; font-weight:600; color:#000000; background-color:#cccccc;\">W</span></p></td>\n"
"<td bgcolor=\"#cccccc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#cccccc;\">3½</span></p></td>\n"
"<td bgcolor=\"#cccccc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#cccccc;\">4</span></p></td>\n"
"<td bgcolor=\"#cccccc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#cccccc;\">4½</span></p></td>\n"
"<td bgcolor=\"#cccccc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#cccccc;\">5</span></p></td>\n"
"<td bgcolor=\"#cccccc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#cccccc;\">5½</span></p></td>\n"
"<td bgcolor=\"#cccccc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#cccccc;\">6</span></p></td>\n"
"<td bgcolor=\"#cccccc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#cccccc;\">6½</span></p></td>\n"
"<td bgcolor=\"#cccccc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#cccccc;\">7</span></p></td>\n"
"<td bgcolor=\"#cccccc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#cccccc;\">7½</span></p></td>\n"
"<td bgcolor=\"#cccccc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#cccccc;\">8</span></p></td>\n"
"<td bgcolor=\"#cccccc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#cccccc;\">8½</span></p></td>\n"
"<td bgcolor=\"#cccccc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#cccccc;\">9</span></p></td>\n"
"<td bgcolor=\"#cccccc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#cccccc;\">10½</span></p></td>\n"
"<td bgcolor=\"#cccccc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#cccccc;\">11½</span></p></td>\n"
"<td bgcolor=\"#cccccc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#cccccc;\">12½</span></p></td>\n"
"<td bgcolor=\"#cccccc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#cccccc;\">14</span></p></td>\n"
"<td bgcolor=\"#cccccc\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; font-weight:600; color:#000000; background-color:#cccccc;\">Australia</span></p></td>\n"
"<td bgcolor=\"#cccccc\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; font-weight:600; color:#000000; background-color:#cccccc;\">W</span></p></td></tr>\n"
"<tr>\n"
"<td rowspan=\"2\" bgcolor=\"#9999cc\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; font-weight:600; color:#000000; background-color:#9999cc;\">U.S. &amp; Canada</span></p></td>\n"
"<td bgcolor=\"#9999cc\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; font-weight:600; color:#000000; background-color:#9999cc;\">M</span></p></td>\n"
"<td bgcolor=\"#9999cc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#9999cc;\">3½</span></p></td>\n"
"<td bgcolor=\"#9999cc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#9999cc;\">4</span></p></td>\n"
"<td bgcolor=\"#9999cc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#9999cc;\">4½</span></p></td>\n"
"<td bgcolor=\"#9999cc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#9999cc;\">5</span></p></td>\n"
"<td bgcolor=\"#9999cc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#9999cc;\">5½</span></p></td>\n"
"<td bgcolor=\"#9999cc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#9999cc;\">6</span></p></td>\n"
"<td bgcolor=\"#9999cc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#9999cc;\">6½</span></p></td>\n"
"<td bgcolor=\"#9999cc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#9999cc;\">7</span></p></td>\n"
"<td bgcolor=\"#9999cc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#9999cc;\">7½</span></p></td>\n"
"<td bgcolor=\"#9999cc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#9999cc;\">8</span></p></td>\n"
"<td bgcolor=\"#9999cc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#9999cc;\">8½</span></p></td>\n"
"<td bgcolor=\"#9999cc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#9999cc;\">9</span></p></td>\n"
"<td bgcolor=\"#9999cc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#9999cc;\">10½</span></p></td>\n"
"<td bgcolor=\"#9999cc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#9999cc;\">11½</span></p></td>\n"
"<td bgcolor=\"#9999cc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#9999cc;\">12½</span></p></td>\n"
"<td bgcolor=\"#9999cc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#9999cc;\">14</span></p></td>\n"
"<td bgcolor=\"#9999cc\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; font-weight:600; color:#000000; background-color:#9999cc;\">U.S. &amp; Canada</span></p></td>\n"
"<td bgcolor=\"#9999cc\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; font-weight:600; color:#000000; background-color:#9999cc;\">M</span></p></td></tr>\n"
"<tr>\n"
"<td bgcolor=\"#ccffcc\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; font-weight:600; color:#000000; background-color:#ccffcc;\">W</span></p></td>\n"
"<td bgcolor=\"#ccffcc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ccffcc;\">5</span></p></td>\n"
"<td bgcolor=\"#ccffcc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ccffcc;\">5½</span></p></td>\n"
"<td bgcolor=\"#ccffcc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ccffcc;\">6</span></p></td>\n"
"<td bgcolor=\"#ccffcc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ccffcc;\">6½</span></p></td>\n"
"<td bgcolor=\"#ccffcc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ccffcc;\">7</span></p></td>\n"
"<td bgcolor=\"#ccffcc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ccffcc;\">7½</span></p></td>\n"
"<td bgcolor=\"#ccffcc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ccffcc;\">8</span></p></td>\n"
"<td bgcolor=\"#ccffcc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ccffcc;\">8½</span></p></td>\n"
"<td bgcolor=\"#ccffcc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ccffcc;\">9</span></p></td>\n"
"<td bgcolor=\"#ccffcc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ccffcc;\">9½</span></p></td>\n"
"<td bgcolor=\"#ccffcc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ccffcc;\">10</span></p></td>\n"
"<td bgcolor=\"#ccffcc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ccffcc;\">10.5</span></p></td>\n"
"<td bgcolor=\"#ccffcc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ccffcc;\">12</span></p></td>\n"
"<td bgcolor=\"#ccffcc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ccffcc;\">13</span></p></td>\n"
"<td bgcolor=\"#ccffcc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ccffcc;\">14</span></p></td>\n"
"<td bgcolor=\"#ccffcc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ccffcc;\">15.5</span></p></td>\n"
"<td bgcolor=\"#ccffcc\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; font-weight:600; color:#000000; background-color:#ccffcc;\">U.S. &amp; Canada</span></p></td>\n"
"<td bgcolor=\"#ccffcc\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; font-weight:600; color:#000000; background-color:#ccffcc;\">W</span></p></td></tr>\n"
"<tr>\n"
"<td bgcolor=\"#ccff99\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; font-weight:600; color:#000000; background-color:#ccff99;\">Russia &amp; Ukraine *</span></p></td>\n"
"<td bgcolor=\"#ccff99\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; font-weight:600; color:#000000; background-color:#ccff99;\">W</span></p></td>\n"
"<td bgcolor=\"#ccff99\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ccff99;\">33½</span></p></td>\n"
"<td bgcolor=\"#ccff99\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ccff99;\">34</span></p></td>\n"
"<td bgcolor=\"#ccff99\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ccff99;\"> </span></p></td>\n"
"<td bgcolor=\"#ccff99\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ccff99;\">35</span></p></td>\n"
"<td bgcolor=\"#ccff99\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ccff99;\"> </span></p></td>\n"
"<td bgcolor=\"#ccff99\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ccff99;\">36</span></p></td>\n"
"<td bgcolor=\"#ccff99\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ccff99;\"> </span></p></td>\n"
"<td bgcolor=\"#ccff99\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ccff99;\">37</span></p></td>\n"
"<td bgcolor=\"#ccff99\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ccff99;\"> </span></p></td>\n"
"<td bgcolor=\"#ccff99\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ccff99;\">38</span></p></td>\n"
"<td bgcolor=\"#ccff99\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ccff99;\"> </span></p></td>\n"
"<td bgcolor=\"#ccff99\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ccff99;\">39</span></p></td>\n"
"<td bgcolor=\"#ccff99\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ccff99;\"> </span></p></td>\n"
"<td bgcolor=\"#ccff99\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ccff99;\"> </span></p></td>\n"
"<td bgcolor=\"#ccff99\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ccff99;\"> </span></p></td>\n"
"<td bgcolor=\"#ccff99\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ccff99;\"> </span></p></td>\n"
"<td bgcolor=\"#ccff99\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; font-weight:600; color:#000000; background-color:#ccff99;\">Russia &amp; Ukraine</span></p></td>\n"
"<td bgcolor=\"#ccff99\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; font-weight:600; color:#000000; background-color:#ccff99;\">W</span></p></td></tr>\n"
"<tr>\n"
"<td colspan=\"2\" bgcolor=\"#ffffff\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; font-weight:600; color:#000000; background-color:#ffffff;\">Korea</span><span style=\" font-family:\'Ubuntu\'; font-size:8pt; font-weight:600; color:#000000;\"> (mm.)</span></p></td>\n"
"<td bgcolor=\"#ffffff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffff;\">228</span></p></td>\n"
"<td bgcolor=\"#ffffff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffff;\">231</span></p></td>\n"
"<td bgcolor=\"#ffffff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffff;\">235</span></p></td>\n"
"<td bgcolor=\"#ffffff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffff;\">238</span></p></td>\n"
"<td bgcolor=\"#ffffff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffff;\">241</span></p></td>\n"
"<td bgcolor=\"#ffffff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffff;\">245</span></p></td>\n"
"<td bgcolor=\"#ffffff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffff;\">248</span></p></td>\n"
"<td bgcolor=\"#ffffff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffff;\">251</span></p></td>\n"
"<td bgcolor=\"#ffffff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffff;\">254</span></p></td>\n"
"<td bgcolor=\"#ffffff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffff;\">257</span></p></td>\n"
"<td bgcolor=\"#ffffff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffff;\">260</span></p></td>\n"
"<td bgcolor=\"#ffffff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffff;\">267</span></p></td>\n"
"<td bgcolor=\"#ffffff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffff;\">273</span></p></td>\n"
"<td bgcolor=\"#ffffff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffff;\">279</span></p></td>\n"
"<td bgcolor=\"#ffffff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffff;\">286</span></p></td>\n"
"<td bgcolor=\"#ffffff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffff;\">292</span></p></td>\n"
"<td colspan=\"2\" bgcolor=\"#ffffff\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; font-weight:600; color:#000000; background-color:#ffffff;\">Korea</span></p></td></tr>\n"
"<tr>\n"
"<td colspan=\"2\" bgcolor=\"#ffcccc\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; font-weight:600; color:#000000; background-color:#ffcccc;\">Inches</span></p></td>\n"
"<td bgcolor=\"#ffcccc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffcccc;\">9</span></p></td>\n"
"<td bgcolor=\"#ffcccc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffcccc;\">9</span><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000;\">1/8</span></p></td>\n"
"<td bgcolor=\"#ffcccc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffcccc;\">9¼</span></p></td>\n"
"<td bgcolor=\"#ffcccc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffcccc;\">9</span><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000;\">3/8</span></p></td>\n"
"<td bgcolor=\"#ffcccc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffcccc;\">9½</span></p></td>\n"
"<td bgcolor=\"#ffcccc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffcccc;\">9</span><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000;\">5/8</span></p></td>\n"
"<td bgcolor=\"#ffcccc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffcccc;\">9¾</span></p></td>\n"
"<td bgcolor=\"#ffcccc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffcccc;\">9</span><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000;\">7/8</span></p></td>\n"
"<td bgcolor=\"#ffcccc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffcccc;\">10</span></p></td>\n"
"<td bgcolor=\"#ffcccc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffcccc;\">10</span><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000;\">1/8</span></p></td>\n"
"<td bgcolor=\"#ffcccc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffcccc;\">10¼</span></p></td>\n"
"<td bgcolor=\"#ffcccc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffcccc;\">10½</span></p></td>\n"
"<td bgcolor=\"#ffcccc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffcccc;\">10¾</span></p></td>\n"
"<td bgcolor=\"#ffcccc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffcccc;\">11</span></p></td>\n"
"<td bgcolor=\"#ffcccc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffcccc;\">11¼</span></p></td>\n"
"<td bgcolor=\"#ffcccc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffcccc;\">11½</span></p></td>\n"
"<td colspan=\"2\" bgcolor=\"#ffcccc\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; font-weight:600; color:#000000; background-color:#ffcccc;\">Inches</span></p></td></tr>\n"
"<tr>\n"
"<td colspan=\"2\" bgcolor=\"#ffffcc\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; font-weight:600; color:#000000; background-color:#ffffcc;\">Centimeters</span></p></td>\n"
"<td bgcolor=\"#ffffcc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffcc;\">22.8</span></p></td>\n"
"<td bgcolor=\"#ffffcc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffcc;\">23.1</span></p></td>\n"
"<td bgcolor=\"#ffffcc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffcc;\">23.5</span></p></td>\n"
"<td bgcolor=\"#ffffcc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffcc;\">23.8</span></p></td>\n"
"<td bgcolor=\"#ffffcc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffcc;\">24.1</span></p></td>\n"
"<td bgcolor=\"#ffffcc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffcc;\">24.5</span></p></td>\n"
"<td bgcolor=\"#ffffcc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffcc;\">24.8</span></p></td>\n"
"<td bgcolor=\"#ffffcc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffcc;\">25.1</span></p></td>\n"
"<td bgcolor=\"#ffffcc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffcc;\">25.4</span></p></td>\n"
"<td bgcolor=\"#ffffcc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffcc;\">25.7</span></p></td>\n"
"<td bgcolor=\"#ffffcc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffcc;\">26</span></p></td>\n"
"<td bgcolor=\"#ffffcc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffcc;\">26.7</span></p></td>\n"
"<td bgcolor=\"#ffffcc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffcc;\">27.3</span></p></td>\n"
"<td bgcolor=\"#ffffcc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffcc;\">27.9</span></p></td>\n"
"<td bgcolor=\"#ffffcc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffcc;\">28.6</span></p></td>\n"
"<td bgcolor=\"#ffffcc\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffcc;\">29.2</span></p></td>\n"
"<td colspan=\"2\" bgcolor=\"#ffffcc\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; font-weight:600; color:#000000; background-color:#ffffcc;\">Centimeters</span></p></td></tr>\n"
"<tr>\n"
"<td colspan=\"2\" bgcolor=\"#ffffff\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; font-weight:600; color:#000000; background-color:#ffffff;\">Mondopoint</span></p></td>\n"
"<td bgcolor=\"#ffffff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffff;\">228</span></p></td>\n"
"<td bgcolor=\"#ffffff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffff;\">231</span></p></td>\n"
"<td bgcolor=\"#ffffff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffff;\">235</span></p></td>\n"
"<td bgcolor=\"#ffffff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffff;\">238</span></p></td>\n"
"<td bgcolor=\"#ffffff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffff;\">241</span></p></td>\n"
"<td bgcolor=\"#ffffff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffff;\">245</span></p></td>\n"
"<td bgcolor=\"#ffffff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffff;\">248</span></p></td>\n"
"<td bgcolor=\"#ffffff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffff;\">251</span></p></td>\n"
"<td bgcolor=\"#ffffff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffff;\">254</span></p></td>\n"
"<td bgcolor=\"#ffffff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffff;\">257</span></p></td>\n"
"<td bgcolor=\"#ffffff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffff;\">260</span></p></td>\n"
"<td bgcolor=\"#ffffff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffff;\">267</span></p></td>\n"
"<td bgcolor=\"#ffffff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffff;\">273</span></p></td>\n"
"<td bgcolor=\"#ffffff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffff;\">279</span></p></td>\n"
"<td bgcolor=\"#ffffff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffff;\">286</span></p></td>\n"
"<td bgcolor=\"#ffffff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; color:#000000; background-color:#ffffff;\">292</span></p></td>\n"
"<td colspan=\"2\" bgcolor=\"#ffffff\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:8pt; font-weight:600; color:#000000; background-color:#ffffff;\">Mondopoint</span></p></td></tr></table></body></html>"))
        self.pushButton.setText(_translate("SizeChart", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SizeChart = QtWidgets.QDialog()
    ui = Ui_SizeChart()
    ui.setupUi(SizeChart)
    SizeChart.show()
    sys.exit(app.exec_())
