# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ProxyConfig.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProxyConfig(object):
    def setupUi(self, ProxyConfig):
        ProxyConfig.setObjectName("ProxyConfig")
        ProxyConfig.resize(822, 520)
        self.verticalLayout = QtWidgets.QVBoxLayout(ProxyConfig)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(ProxyConfig)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(25)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 1, 1, 1)
        self.SeparatorLabel = QtWidgets.QLabel(ProxyConfig)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SeparatorLabel.sizePolicy().hasHeightForWidth())
        self.SeparatorLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        self.SeparatorLabel.setFont(font)
        self.SeparatorLabel.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.SeparatorLabel.setStyleSheet("margin-top: 15px; margin-bottom: auto;")
        self.SeparatorLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.SeparatorLabel.setObjectName("SeparatorLabel")
        self.gridLayout.addWidget(self.SeparatorLabel, 1, 0, 1, 1)
        self.SeparatorComboBox = QtWidgets.QComboBox(ProxyConfig)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        self.SeparatorComboBox.setFont(font)
        self.SeparatorComboBox.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.SeparatorComboBox.setStyleSheet("")
        self.SeparatorComboBox.setObjectName("SeparatorComboBox")
        self.SeparatorComboBox.addItem("")
        self.SeparatorComboBox.addItem("")
        self.SeparatorComboBox.addItem("")
        self.SeparatorComboBox.addItem("")
        self.gridLayout.addWidget(self.SeparatorComboBox, 1, 2, 1, 1)
        self.ProxyTypeLabel = QtWidgets.QLabel(ProxyConfig)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ProxyTypeLabel.sizePolicy().hasHeightForWidth())
        self.ProxyTypeLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        self.ProxyTypeLabel.setFont(font)
        self.ProxyTypeLabel.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.ProxyTypeLabel.setStyleSheet("margin-top: 15px; margin-bottom: auto;")
        self.ProxyTypeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ProxyTypeLabel.setObjectName("ProxyTypeLabel")
        self.gridLayout.addWidget(self.ProxyTypeLabel, 2, 0, 1, 1)
        self.ProfileName = QtWidgets.QLineEdit(ProxyConfig)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        self.ProfileName.setFont(font)
        self.ProfileName.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.ProfileName.setStyleSheet("")
        self.ProfileName.setObjectName("ProfileName")
        self.gridLayout.addWidget(self.ProfileName, 0, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 1, 1, 1)
        self.ProxyTypeComboBox = QtWidgets.QComboBox(ProxyConfig)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        self.ProxyTypeComboBox.setFont(font)
        self.ProxyTypeComboBox.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.ProxyTypeComboBox.setStyleSheet("")
        self.ProxyTypeComboBox.setObjectName("ProxyTypeComboBox")
        self.ProxyTypeComboBox.addItem("")
        self.ProxyTypeComboBox.addItem("")
        self.gridLayout.addWidget(self.ProxyTypeComboBox, 2, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 2, 1, 1, 1)
        self.ProfileNameLabel = QtWidgets.QLabel(ProxyConfig)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ProfileNameLabel.sizePolicy().hasHeightForWidth())
        self.ProfileNameLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        self.ProfileNameLabel.setFont(font)
        self.ProfileNameLabel.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.ProfileNameLabel.setStyleSheet("margin-top: 15px; margin-bottom: auto;")
        self.ProfileNameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ProfileNameLabel.setObjectName("ProfileNameLabel")
        self.gridLayout.addWidget(self.ProfileNameLabel, 0, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.pushButton = QtWidgets.QPushButton(ProxyConfig)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("margin-left: 120; margin-right:120; margin-top: 5; margin-bottom: 5; height: 40px; padding-left: 15px; padding-right:15px;")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_3.addWidget(self.pushButton)
        self.LogOutput = QtWidgets.QTextEdit(ProxyConfig)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        self.LogOutput.setFont(font)
        self.LogOutput.setFocusPolicy(QtCore.Qt.NoFocus)
        self.LogOutput.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.LogOutput.setToolTipDuration(0)
        self.LogOutput.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.LogOutput.setObjectName("LogOutput")
        self.verticalLayout_3.addWidget(self.LogOutput)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(ProxyConfig)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.ProxyInput = QtWidgets.QTextBrowser(ProxyConfig)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ProxyInput.sizePolicy().hasHeightForWidth())
        self.ProxyInput.setSizePolicy(sizePolicy)
        self.ProxyInput.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.ProxyInput.setUndoRedoEnabled(True)
        self.ProxyInput.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextEditable|QtCore.Qt.TextEditorInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.ProxyInput.setObjectName("ProxyInput")
        self.verticalLayout_2.addWidget(self.ProxyInput)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.cancel = QtWidgets.QPushButton(ProxyConfig)
        self.cancel.setObjectName("cancel")
        self.horizontalLayout_2.addWidget(self.cancel)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(ProxyConfig)
        QtCore.QMetaObject.connectSlotsByName(ProxyConfig)

    def retranslateUi(self, ProxyConfig):
        _translate = QtCore.QCoreApplication.translate
        ProxyConfig.setWindowTitle(_translate("ProxyConfig", "Dialog"))
        self.label.setText(_translate("ProxyConfig", "Proxy config"))
        self.SeparatorLabel.setText(_translate("ProxyConfig", "Separator"))
        self.SeparatorComboBox.setItemText(0, _translate("ProxyConfig", "(Default) String"))
        self.SeparatorComboBox.setItemText(1, _translate("ProxyConfig", "*"))
        self.SeparatorComboBox.setItemText(2, _translate("ProxyConfig", ";"))
        self.SeparatorComboBox.setItemText(3, _translate("ProxyConfig", "-"))
        self.ProxyTypeLabel.setText(_translate("ProxyConfig", "Proxy type"))
        self.ProxyTypeComboBox.setItemText(0, _translate("ProxyConfig", "PROXY:PORT"))
        self.ProxyTypeComboBox.setItemText(1, _translate("ProxyConfig", "PROXY:PORT:LOGIN:PASS"))
        self.ProfileNameLabel.setText(_translate("ProxyConfig", "Profile name"))
        self.pushButton.setText(_translate("ProxyConfig", "Add proxy profile"))
        self.label_2.setText(_translate("ProxyConfig", "Please enter your proxies here:"))
        self.ProxyInput.setHtml(_translate("ProxyConfig", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.cancel.setText(_translate("ProxyConfig", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ProxyConfig = QtWidgets.QDialog()
    ui = Ui_ProxyConfig()
    ui.setupUi(ProxyConfig)
    ProxyConfig.show()
    sys.exit(app.exec_())
